import { defineConfig } from "vite-plus";

const task = (command: string, dependsOn: string[] = []) => ({ command, dependsOn, cache: false as const });
export default defineConfig({
  defaultPackage: "./apps/web",
  fmt: {},
  lint: { options: { typeAware: true, typeCheck: true } },
  run: {
    cache: false,
    tasks: {
      "css:sources": task("node tools/tailwind-sources/index.ts"),
      "check:css-sources": task("node tools/tailwind-sources/index.ts --check"),
      "test:css-sources": task("node --test tools/tailwind-sources/*.test.ts"),
      generate: task("node scripts/generate.ts"),
      "check:rust": task("node scripts/rust.ts clippy --workspace --all-targets --features product-source-ingestion/kafka-canonical"),
      "test:rust": task("node scripts/rust.ts test --workspace --tests --no-fail-fast && node scripts/rust.ts test -p view-server-app --no-default-features --test v12_socket"),
      "test:infra": task("node --test scripts/test_*.ts tests/integration/*_test.ts", ["test:css-sources"]),
      "build:wasm": task("vp run @bruno/rust-view-server#build:wasm"),
      "stage:client-wasm": task("node scripts/stage-client-wasm.ts", ["build:wasm"]),
      "build:native": task("node scripts/rust.ts build --locked --release -p view-server-app -p product-source-ingestion --features product-source-ingestion/kafka-canonical --bin view_server --example seed_producer"),
      "check:policy": task("node scripts/repository-policy.ts && node scripts/package-boundaries.ts", ["check:css-sources"]),
      "check:tooling": task("vp exec tsc -p tsconfig.tooling.json && vp exec tsc -p packages/view-server-client/tsconfig.tooling.json && vp exec tsc -p packages/table/tsconfig.tooling.json", ["build:packages"]),
      "test:sdk-runtime": task("node --test packages/view-server-client/scripts/*.test.ts"),
      check: task("vp exec tsc --noEmit -p packages/view-server-client/tsconfig.json && vp exec tsc --noEmit -p packages/view-server-client/tsconfig.contracts.json && vp exec tsc --noEmit -p packages/view-server-client/tsconfig.emitted.json && vp run @bruno/table#test:types:source && vp run @bruno/table#test:types:emitted && vp run @bruno/table#test:types:rust && vp exec tsc -p apps/web/tsconfig.json --noEmit", ["generate", "build:packages", "check:rust", "check:tooling", "check:policy"]),
      "build:sdk": task("vp -C packages/view-server-client run build:package", ["generate", "stage:client-wasm"]),
      "build:packages": task("vp run @bruno/shadcn#build && vp run @bruno/table#build", ["build:sdk"]),
      "test:packaged": task("vp run @bruno/view-server-client#test:packed && vp run @bruno/table#test:packed && vp run @bruno/table#test:compiler:production", ["build:packages"]),
      "test:e2e": task("node scripts/e2e.ts", ["build:packages"]),
      verify: task("vp run generate && vp run build && vp run check && vp run test && vp run test:packaged && vp run test:e2e"),
      "test:ui": task("vp run @bruno/shadcn#test:browser"),
      "test:provider": task("vp -C packages/view-server-client exec tsc --noEmit -p tsconfig.browser.json && vp -C packages/view-server-client test run --config browser.config.ts", ["build:sdk"]),
      "test:tooling": task("vp run @bruno/table#test:build:contracts && vp run @bruno/table#test:release:package", ["build:packages"]),
      "test:sdk": task("vp test run packages/view-server-client/src/complete-client.test.ts"),
      test: task("vp run @bruno/table#test --run && vp run @bruno/table#test:browser", ["generate", "test:rust", "test:infra", "test:sdk", "test:sdk-runtime", "test:provider", "test:ui", "test:tooling"]),
      build: task("vp run @bruno/shadcn#build && vp run @bruno/table#build && vp run @bruno/web#build", ["generate", "build:sdk", "build:native"]),
      dev: task("node scripts/dev.ts --no-build", ["build"]),
      seed: task("node scripts/seed.ts"),
      "kafka:init": task("node scripts/kafka.ts init"),
      "kafka:up": task("node scripts/kafka.ts up"),
      "kafka:down": task("node scripts/kafka.ts down"),
      "kafka:status": task("node scripts/kafka.ts status"),
      "kafka:reset": task("node scripts/kafka.ts reset"),
      "kafka:probe": task("node scripts/rust.ts run -p product-source-ingestion --features kafka-canonical --example orbstack_probe"),
    },
  },
});
