import {createElement as h,useEffect,useState} from 'react';
import {render} from 'vitest-browser-react';
import {expect,it,vi} from 'vite-plus/test';
import {BrowserProductProvider,ProductProvider,createTopicHooks,type TopicRuntimeQuery} from './product-provider';
import {orders,positions} from './topic-examples';
import {schemaFingerprint} from './topic-schema';
class WorkerHarness{static all:WorkerHarness[]=[];onmessage:((e:MessageEvent)=>void)|null=null;onerror:unknown;onmessageerror:unknown;sent:any[]=[];dead=false;constructor(){WorkerHarness.all.push(this)}postMessage(v:unknown){this.sent.push(v)}terminate(){this.dead=true}receive(v:unknown){this.onmessage?.({data:v}as MessageEvent)}ack(r:any,rows:any[]=[]){const sub=r.command.subscription;this.receive({type:'ack',id:r.id,traceparent:r.traceparent,acquisitions:{[sub]:r.acquisition},results:{[sub]:{subscription:sub,topic:r.command.query?.topic,schema:r.command.query?.schema,query_generation:r.acquisition,sequence:r.id,start_rank:r.command.query?.offset??0,total_rows:rows.length,version:r.id,keys:rows.map((_,i)=>'k'+i),rows}}})}}
async function setup(){const catalog={orders:{schema:orders,fingerprint:await schemaFingerprint(orders)},positions:{schema:positions,fingerprint:await schemaFingerprint(positions)}};WorkerHarness.all=[];vi.stubGlobal('Worker',WorkerHarness);const provider=new BrowserProductProvider({mode:'remote',url:'ws://127.0.0.1:12345/v15',token:'test',catalog,recovery:{initialDelayMs:5,maxDelayMs:5,budgetMs:100,maxAttempts:4}});return {provider,catalog,hooks:createTopicHooks(catalog)}}
it('shares one provider for different schemas and clears whole-hook data on topic replacement',async()=>{const{provider:p,hooks}=await setup();let choose:(v:boolean)=>void=()=>{};
 function App(){const[second,setSecond]=useState(false);choose=setSecond;const a=second?hooks.useLiveQuery('positions',{select:['symbol'],orderBy:[]}):hooks.useLiveQuery('orders',{select:['customer'],orderBy:[]});const vp=hooks.useLiveQueryViewport('positions');useEffect(()=>{const g=vp.viewport.replace({window:{firstRow:0,lastRow:1},query:{select:['risk'],orderBy:[]},sink:{setRowCount(){},setRowData(){}}});return()=>g.release()},[vp.viewport]);return h('output',null,JSON.stringify({status:a.status,rows:a.rows}));}
 const screen=await render(h(ProductProvider,{provider:p,children:h(App)}));try{const w=WorkerHarness.all[0];w.receive({type:'ready'});await expect.poll(()=>w.sent.filter(x=>x.type==='apply').length).toBe(2);for(const r of w.sent.filter(x=>x.type==='apply'))w.ack(r,r.command.query.topic==='orders'?[{customer:'Alice'}]:[{risk:1.5}]);await expect.element(screen.getByRole('status')).toMatchTextContent(/Alice/);expect(WorkerHarness.all.length).toBe(1);choose(true);await expect.element(screen.getByRole('status')).not.toMatchTextContent(/Alice/);await expect.poll(()=>w.sent.filter(x=>x.type==='apply'&&x.command.command==='open'&&x.command.query.topic==='positions').length).toBe(2);const r=w.sent.filter(x=>x.type==='apply'&&x.command.command==='open').at(-1);w.ack(r,[{symbol:'XYZ'}]);await expect.element(screen.getByRole('status')).toMatchTextContent(/XYZ/);}finally{await screen.unmount();p.dispose();vi.unstubAllGlobals()}});
it('R1-MIXED cross-topic query/window intent emits the full new dataset and settles once',async()=>{const{provider:p,catalog}=await setup();const q=(topic:'orders'|'positions'):TopicRuntimeQuery=>({topic,schema:catalog[topic].fingerprint,select:topic==='orders'?['customer']:['symbol'],order_by:[],offset:0,limit:2});const delivered:any[]=[];let armed=false,nested:Promise<unknown>|undefined;const listener=Object.assign((r:any)=>delivered.push(r),{onStatus(status:string){if(armed&&status==='loading'){armed=false;nested=p.apply({command:'change_window',subscription:'shared',offset:8,limit:2})}}});const release=p.watch('shared',q('orders'),listener);try{const w=WorkerHarness.all[0];w.receive({type:'ready'});await expect.poll(()=>w.sent.filter(x=>x.type==='apply').length).toBe(1);w.ack(w.sent.at(-1),[{customer:'Alice'}]);await expect.poll(()=>delivered.length).toBe(1);armed=true;const outer=p.apply({command:'change_query',subscription:'shared',query:q('positions')}).catch(e=>e.code);expect(await outer).toBe('read_superseded');const request=w.sent.at(-1);expect(request.command.command).toBe('change_query');expect(request.command.query).toMatchObject({topic:'positions',schema:catalog.positions.fingerprint,offset:8,select:['symbol']});w.ack(request,[]);await nested;expect(delivered.at(-1).topic).toBe('positions');await expect(p.apply({command:'change_query',subscription:'shared',query:{...q('orders'),select:['symbol']}})).rejects.toThrow();expect(p.admission.outstanding).toBe(0);}finally{release();p.dispose();vi.unstubAllGlobals()}});
it('catalog provider H1 health disposal fences stale attempts and settles readiness',async()=>{const{provider:p}=await setup();try{const w=WorkerHarness.all[0];w.receive({type:'ready'});await p.ready;const ready=p.ready;const off=p.subscribeHealth(()=>{if(p.getHealthSnapshot().status==='stale')p.dispose()});w.receive({type:'health',snapshot:{version:1,instance:'old',sequence:1,sources:[],dependencies:[]}});w.receive({type:'fatal',recoverable:true,error:'network',code:'network'});await new Promise(r=>setTimeout(r,180));w.receive({type:'ready'});expect(p.ready).toBe(ready);expect(WorkerHarness.all.length).toBe(1);expect(p.connectionDiagnostics.terminalCode).toBe('disposed');expect(p.getHealthSnapshot().status).toBe('closed');expect(p.admission.outstanding).toBe(0);off()}finally{p.dispose();vi.unstubAllGlobals()}});
