#![cfg(feature="kafka-canonical")]
use product_source_ingestion::{generic_kafka::SourceConfig,generic_source::Decoder,generic_evolution::{admit,SourceDecoder}};
use rust_differential_product_core::{schema::{Schema,Catalog,Manifest,Topic},generic::{Mutation,Runtime}};
use serde_json::{json,Value};
fn config()->(SourceConfig,Schema){let b:Value=serde_json::from_str(include_str!("../../../../../fixtures/evolution/bindings.json")).unwrap();let old=&b["old"]["evolution.Row"];let new=&b["next"]["evolution.Row"];let key=&b["old"]["evolution.Key"];let schema=Schema::new(serde_json::from_value(new["schema"].clone()).unwrap()).unwrap();let c=serde_json::from_value(json!({"topic":"evolved","schema":schema.fingerprint(),"brokers":"127.0.0.1:9092","source_topic":"fixture-source","state_topic":"fixture-state","source_incarnation":"fixture","group":"fixture-owner","initialize_empty":false,"partitions":[0,1],"max_rows":100,"key_descriptor":key["descriptor"],"value_descriptor":new["descriptor"],"mapping":new["mapping"],"key_fields":key["key_fields"],"identity":{"source_policy":"compact","components":[{"source":"key","field":"id"}]},"readiness":{"enter_offset_distance":1,"exit_offset_distance":2,"max_sample_age_ms":2000,"enter_hold_ms":0,"exit_hold_ms":0},"evolution":{"definition":old["schema"],"value_descriptor":old["descriptor"],"mapping":old["mapping"]}})).unwrap();(c,schema)}
fn frame(id:u32,bytes:&[u8])->Vec<u8>{let mut v=vec![0];v.extend(id.to_be_bytes());v.push(0);v.extend(bytes);v}
#[test]fn mixed_descriptors_missing_empty_replacement_and_tombstone(){let(c,s)=config();let(p,old,d)=admit(&c,&s).unwrap().unwrap();let current=Decoder::new_identity(s.clone(),&c.key_descriptor,&c.value_descriptor,c.mapping.clone(),c.key_fields.clone(),c.identity.clone().unwrap()).unwrap();let decoder=SourceDecoder::new(current,s.clone(),Some((p.value_descriptor.schema_id,d)));let key=frame(c.key_descriptor.schema_id,&[10,1,b'a']);
 let old_payload=frame(p.value_descriptor.schema_id,&[10,1,b'L',18,3,10,1,b'N']);let new_payload=frame(c.value_descriptor.schema_id,&[10,1,b'L',18,5,10,1,b'N',18,0]);
 let a=decoder.decode(Some(&key),Some(&old_payload)).unwrap();let b=decoder.decode(Some(&key),Some(&new_payload)).unwrap();assert_eq!(a.0,b.0);assert_eq!(a.1,b.1);let Mutation::Upsert{row:ar}=a.2 else{panic!()};let Mutation::Upsert{row:br}=b.2 else{panic!()};assert!(ar["detail"].get("note").is_none());assert_eq!(br["detail"]["note"],"");assert!(old.row(&br).is_err());
 let catalog=Catalog::new(Manifest{format:1,schemas:vec![s.definition().clone()],topics:vec![Topic{topic:c.topic.clone(),schema:s.fingerprint().into()}]}).unwrap();let mut runtime=Runtime::new(catalog,100).unwrap();runtime.apply_committed(&c.topic,s.fingerprint(),&[Mutation::Upsert{row:ar}]).unwrap();runtime.open("q",&c.topic,s.fingerprint(),serde_json::from_value(json!({"select":["detail.note"],"order_by":[]})).unwrap()).unwrap();assert_eq!(runtime.read("q",0,10,65536).unwrap().rows,vec![json!({"detail":{}})]);runtime.apply_committed(&c.topic,s.fingerprint(),&[Mutation::Upsert{row:br}]).unwrap();assert_eq!(runtime.read("q",0,10,65536).unwrap().rows,vec![json!({"detail":{"note":""}})]);let deleted=decoder.decode(Some(&key),None).unwrap();runtime.apply_committed(&c.topic,s.fingerprint(),&[deleted.2]).unwrap();assert!(runtime.read("q",0,10,65536).unwrap().rows.is_empty());assert!(decoder.decode(Some(&key),Some(&frame(999,&[]))).is_err());}
#[test]fn incompatible_or_unbound_transition_rejects(){let(c,s)=config();assert!(admit(&c,&s).is_ok());let mut bad=c.clone();bad.initialize_empty=true;assert!(admit(&bad,&s).is_err());let mut bad=c.clone();bad.value_descriptor.schema_id=bad.evolution.as_ref().unwrap().value_descriptor.schema_id;assert!(admit(&bad,&s).is_err());let mut bad=c.clone();bad.mapping[0].tag+=1;assert!(admit(&bad,&s).is_err());let mut bad=c.clone();bad.evolution.as_mut().unwrap().definition.fields[0].nullable=true;assert!(admit(&bad,&s).is_err());}
