import {createElement as h,useEffect} from 'react';import {render} from 'vitest-browser-react';import {expect,it,vi} from 'vite-plus/test';
import {BrowserProductProvider,ProductProvider,createTopicHooks,type TopicRuntimeQuery} from './product-provider';import {catalog} from './generated/topics';import {groupId,resultShape} from './topic-schema';
class Peer{static all:Peer[]=[];onmessage:((e:MessageEvent)=>void)|null=null;sent:any[]=[];constructor(){Peer.all.push(this)}postMessage(v:unknown){this.sent.push(v)}terminate(){}receive(v:unknown){this.onmessage?.({data:v}as MessageEvent)}ack(r:any,result:any){this.receive({type:'ack',id:r.id,traceparent:r.traceparent,acquisitions:{[r.command.subscription]:r.acquisition},results:{[r.command.subscription]:result}})}}
const query={groupBy:['note'],aggregates:{n:{aggFunc:'count'}},orderBy:[]}as const;
function result(r:any,n='1'){const row={note:null,n};return{subscription:r.command.subscription,topic:'orders',schema:catalog.orders.fingerprint,result_kind:'grouped_v1',result_shape:resultShape('orders',catalog.orders.fingerprint,query),query_generation:r.acquisition,sequence:1,start_rank:0,total_rows:1,version:1,keys:[groupId('orders',catalog.orders.fingerprint,catalog.orders.schema,query,row)],rows:[row]};}
it('mounted whole, viewport and helper receive complete group rows; isolated query failure keeps raw consumer alive',async()=>{
 Peer.all=[];vi.stubGlobal('Worker',Peer);const p=new BrowserProductProvider({mode:'remote',url:'ws://127.0.0.1:1/v15',token:'test',catalog}),hooks=createTopicHooks(catalog);let whole:any,helper:any,view:any,raw:any;
 function App(){whole=hooks.useLiveQuery('orders',query);raw=hooks.useLiveQuery('orders',{select:['customer'],orderBy:[]});const vp=hooks.useLiveQueryViewport('orders');helper=vp.useWholeResult(query);useEffect(()=>{const g=vp.viewport.replace({query,window:{firstRow:0,lastRow:1},sink:{setRowCount(){},setRowData(rows){view=rows;}}});return()=>g.release();},[vp.viewport]);return h('output',null,whole.status+':'+raw.status);}
 const screen=await render(h(ProductProvider,{provider:p,children:h(App)}));try{const w=Peer.all[0];w.receive({type:'ready'});await expect.poll(()=>w.sent.filter(v=>v.type==='apply').length).toBe(4);const requests=w.sent.filter(v=>v.type==='apply');for(const r of requests){const grouped=!!r.command.query.group_by;const v=result(r);w.ack(r,grouped?v:{...v,result_kind:undefined,result_shape:undefined,keys:['rid2:0101010000000161'],rows:[{customer:'Alice'}]});}await expect.poll(()=>whole.rows.length).toBe(1);await expect.poll(()=>Object.keys(view??{}).length).toBe(1);expect(helper.rows).toEqual(whole.rows);expect(view[0]).toEqual(whole.rows[0]);expect(Object.keys(whole.rows[0])).toEqual(['note','n','rowId']);expect(Object.getOwnPropertyDescriptor(whole.rows[0],'rowId')?.writable).toBe(false);
 const r=requests.find(v=>v.command.query.group_by&&v.command.subscription.includes('consumer'));w.receive({type:'query_error',subscription:r.command.subscription,acquisition:r.acquisition,error:'aggregate query failed: bounded'});await expect.poll(()=>whole.status).toBe('error');expect(raw.status).toBe('ready');expect(raw.rows[0].customer).toBe('Alice');expect(Peer.all.length).toBe(1);
 }finally{await screen.unmount();p.dispose();vi.unstubAllGlobals();}
});
it('R1 grouped replacement preserves full query in nested window and rejects invalid admission without losing acquisition',async()=>{
 Peer.all=[];vi.stubGlobal('Worker',Peer);const p=new BrowserProductProvider({mode:'remote',url:'ws://127.0.0.1:1/v15',token:'test',catalog});const raw:TopicRuntimeQuery={topic:'orders',schema:catalog.orders.fingerprint,select:['customer'],order_by:[],offset:0,limit:2};const grouped:TopicRuntimeQuery={topic:'orders',schema:catalog.orders.fingerprint,group_by:['note'],aggregates:{n:{aggFunc:'count'}},order_by:[],offset:0,limit:2};let armed=false,nested:Promise<unknown>|undefined;const seen:any[]=[];const listener=Object.assign((v:unknown)=>seen.push(v),{onStatus(s:string){if(armed&&s==='loading'){armed=false;nested=p.apply({command:'change_window',subscription:'q',offset:5,limit:2});}}});const release=p.watch('q',raw,listener);
 try{const w=Peer.all[0];w.receive({type:'ready'});await expect.poll(()=>w.sent.filter(v=>v.type==='apply').length).toBe(1);const r=w.sent.at(-1);w.ack(r,{...result(r),result_kind:undefined,result_shape:undefined,rows:[{customer:'A'}],keys:['rid2:0101010000000161']});await expect.poll(()=>seen.length).toBe(1);armed=true;expect(await p.apply({command:'change_query',subscription:'q',query:grouped}).catch(e=>e.code)).toBe('read_superseded');await expect.poll(()=>w.sent.filter(v=>v.type==='apply').length).toBe(2);const next=w.sent.at(-1);expect(next.command.query).toMatchObject({...grouped,offset:5});w.ack(next,{...result(next),start_rank:5,rows:[],keys:[]});await nested;expect(seen.at(-1).result_kind).toBe('grouped_v1');await expect(p.apply({command:'change_query',subscription:'q',query:{...grouped,select:['customer']}})).rejects.toThrow();expect(p.admission.outstanding).toBe(0);
 }finally{release();p.dispose();vi.unstubAllGlobals();}
});
