import {defineCatalog,defineSchema,validName,validateQuery,validateRow,validateGroupedRow,resultShape,groupId,schemaBytes,queryFields,type BrowserCatalog,type Schema,type SchemaField,type ProjectedFields,type Field,type FieldName,type TopicQuery,type QueryResult,type QueryCheck,type AggregateQuery} from './topic-schema.ts';
export type JoinWire={readonly version:1;readonly left_alias:string;readonly right:{readonly topic:string;readonly schema:string;readonly alias:string};readonly kind:'inner'|'left';readonly cardinality:'many_to_one';readonly on:{readonly left:string;readonly right:string};readonly limits:{readonly max_left_rows_per_key:number;readonly max_output_rows:number}};
export type JoinSpec<C extends BrowserCatalog>={readonly left:{readonly topic:keyof C&string;readonly as:string};readonly right:{readonly topic:keyof C&string;readonly as:string};readonly kind:'inner'|'left';readonly cardinality:'many_to_one';readonly on:{readonly left:string;readonly right:string};readonly limits:{readonly maxLeftRowsPerKey:number;readonly maxOutputRows:number}};
type L<C extends BrowserCatalog,D extends JoinSpec<C>>=C[D['left']['topic']]['schema'];type R<C extends BrowserCatalog,D extends JoinSpec<C>>=C[D['right']['topic']]['schema'];
type At<S extends Schema,N extends string>=Extract<SchemaField<S>,{name:N}>;
type Domain<F extends Field>=F['kind'] extends 'enum'?F extends {enum_domain:infer E}?[F['kind'],E]:never:F['kind'];
type DefinitionCheck<C extends BrowserCatalog,D extends JoinSpec<C>>=D['left']['topic'] extends D['right']['topic']?never:D['left']['as'] extends D['right']['as']?never:D['on']['left'] extends FieldName<L<C,D>>?D['on']['right'] extends FieldName<R<C,D>>?[Domain<At<L<C,D>,D['on']['left']>>] extends [Domain<At<R<C,D>,D['on']['right']>>]?[Domain<At<R<C,D>,D['on']['right']>>] extends [Domain<At<L<C,D>,D['on']['left']>>]?unknown:never:never:never:never;
type Qualified<F extends Field,A extends string,N extends boolean>=F extends Field?{readonly kind:F['kind'];readonly optional:F['optional'];readonly name:`${A}.${F['name']}`;readonly nullable:true extends N?true:F['nullable']}:never;
type Parents<S extends Schema,A extends string>={readonly path:A;readonly message:'JoinSource';readonly required:true}|(S extends {expansion:infer E extends NonNullable<Schema['expansion']>}?E['parents'][number] extends infer P?P extends {path:infer Path extends string;message:infer M extends string;required:infer V extends boolean}?{readonly path:`${A}.${Path}`;readonly message:M;readonly required:V}:never:never:never);
type Leaves<S extends Schema,A extends string>=SchemaField<S> extends infer F?F extends Field?{readonly path:`${A}.${F['name']}`;readonly presence:'explicit';readonly required:S extends {expansion:infer E extends NonNullable<Schema['expansion']>}?Extract<E['leaves'][number],{path:F['name']}>['required']:F['optional'] extends false?true:false;readonly enum_domain:F extends {enum_domain:infer Domain extends string}?Domain:never}:never:never;
export type JoinedSchema<C extends BrowserCatalog,D extends JoinSpec<C>,Nulls extends boolean=true>={readonly format:3;readonly version:3;readonly id:string;readonly key:'rowId';readonly fields:readonly (Qualified<SchemaField<L<C,D>>,D['left']['as'],false>|Qualified<SchemaField<R<C,D>>,D['right']['as'],Nulls extends true?'left' extends D['kind']?true:false:false>)[];readonly expansion:{readonly message:'JoinResult';readonly parents:readonly (Parents<L<C,D>,D['left']['as']>|Parents<R<C,D>,D['right']['as']>)[];readonly leaves:readonly (Leaves<L<C,D>,D['left']['as']>|Leaves<R<C,D>,D['right']['as']>)[];readonly enums:Readonly<Record<string,Readonly<Record<string,number>>>>}};
export type JoinResult<C extends BrowserCatalog,D extends JoinSpec<C>,Q extends TopicQuery<JoinedSchema<C,D>>>=Q extends {select:infer T extends readonly string[]}?{readonly rowId:string}&{[K in keyof ProjectedFields<JoinedSchema<C,D,false>,T>]:ProjectedFields<JoinedSchema<C,D,false>,T>[K]|(K extends D['right']['as']?'left' extends D['kind']?null:never:never)}:QueryResult<JoinedSchema<C,D>,Q>;
export type JoinQueryCheck<C extends BrowserCatalog,D extends JoinSpec<C>,Q>=QueryCheck<Q,JoinedSchema<C,D>>&(Q extends {aggregates:infer A}?Extract<keyof A,D['left']['as']|D['right']['as']> extends never?unknown:never:unknown);
export type JoinHandle<C extends BrowserCatalog=BrowserCatalog,D extends JoinSpec<C>=JoinSpec<C>>={readonly joinDefinition:D;readonly topic:D['left']['topic'];readonly fingerprint:string;readonly wire:JoinWire;readonly signature:string;readonly internalTopic:string;readonly internalFingerprint:string;readonly schema:JoinedSchema<C,D>;readonly sourceCatalog:C};
function canonical(v:unknown):unknown{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,v])=>[k,canonical(v)]));return v;}
export function joinSignature(topic:string,fingerprint:string,wire:JoinWire):string{return JSON.stringify(canonical([1,topic,fingerprint,wire]));}
// Synchronous SHA-256 for deterministic shape identities; checked against WebCrypto
// in tests. This is not an authentication primitive or a new transport protection.
export function identityHash(text:string):string{
 const k=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
 const bytes=new TextEncoder().encode(text),buffer=new Uint8Array(Math.ceil((bytes.length+9)/64)*64);buffer.set(bytes);buffer[bytes.length]=128;const view=new DataView(buffer.buffer);view.setBigUint64(buffer.length-8,BigInt(bytes.length)*8n);const h=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19],ro=(x:number,n:number)=>(x>>>n)|(x<<(32-n));
 for(let start=0;start<buffer.length;start+=64){const w=new Uint32Array(64);for(let i=0;i<16;i++)w[i]=view.getUint32(start+i*4);for(let i=16;i<64;i++){const x=w[i-15],y=w[i-2];w[i]=w[i-16]+(ro(x,7)^ro(x,18)^(x>>>3))+w[i-7]+(ro(y,17)^ro(y,19)^(y>>>10));}let[a,b,c,d,e,f,g,z]=h;for(let i=0;i<64;i++){const t=(z+(ro(e,6)^ro(e,11)^ro(e,25))+((e&f)^(~e&g))+k[i]+w[i])|0,u=((ro(a,2)^ro(a,13)^ro(a,22))+((a&b)^(a&c)^(b&c)))|0;z=g;g=f;f=e;e=(d+t)|0;d=c;c=b;b=a;a=(t+u)|0;}[a,b,c,d,e,f,g,z].forEach((v,i)=>h[i]=(h[i]+v)|0);}return h.map(x=>(x>>>0).toString(16).padStart(8,'0')).join('');
}
export function joinSchema(catalog:BrowserCatalog,topic:string,wire:JoinWire):{schema:Schema;signature:string;internalTopic:string;internalFingerprint:string}{
 const left=catalog[topic],right=catalog[wire.right.topic];if(!left||!right||right.fingerprint!==wire.right.schema||wire.version!==1||wire.cardinality!=='many_to_one'||!['left','inner'].includes(wire.kind)||topic===wire.right.topic||!validName(wire.left_alias)||!validName(wire.right.alias)||[wire.left_alias,wire.right.alias].includes('rowId')||wire.left_alias===wire.right.alias||!Number.isSafeInteger(wire.limits.max_left_rows_per_key)||wire.limits.max_left_rows_per_key<1||wire.limits.max_left_rows_per_key>1024||!Number.isSafeInteger(wire.limits.max_output_rows)||wire.limits.max_output_rows<1||wire.limits.max_output_rows>100000)throw Error('join definition');
 const lf=left.schema.fields.find(f=>f.name===wire.on.left),rf=right.schema.fields.find(f=>f.name===wire.on.right);if(!lf||!rf||lf.kind!==rf.kind||left.schema.expansion?.leaves.find(l=>l.path===lf.name)?.enum_domain!==right.schema.expansion?.leaves.find(l=>l.path===rf.name)?.enum_domain)throw Error('join key domain');
 const signature=joinSignature(topic,left.fingerprint,wire),internalTopic='j'+identityHash(signature).slice(0,16);const fields:Field[]=[],parents:NonNullable<Schema['expansion']>['parents'][number][]=[],leaves:NonNullable<Schema['expansion']>['leaves'][number][]=[],enums:Record<string,Readonly<Record<string,number>>>={};
 for(const [schema,alias,rightSide]of [[left.schema,wire.left_alias,false],[right.schema,wire.right.alias,true]] as const){parents.push({path:alias,message:'JoinSource',required:true});for(const p of schema.expansion?.parents??[])parents.push({...p,path:alias+'.'+p.path});for(const [domain,labels]of Object.entries(schema.expansion?.enums??{})){if(enums[domain]&&JSON.stringify(canonical(enums[domain]))!==JSON.stringify(canonical(labels)))throw Error('join enum definition conflict');enums[domain]=labels;}for(const f of schema.fields){const l=schema.expansion?.leaves.find(l=>l.path===f.name);fields.push({name:alias+'.'+f.name,kind:f.kind,optional:f.optional,nullable:f.nullable||rightSide&&wire.kind==='left'});leaves.push({path:alias+'.'+f.name,presence:'explicit',required:l?.required??!f.optional,...(l?.enum_domain?{enum_domain:l.enum_domain}:{})});}}
 const schema=defineSchema({format:3,version:3,id:internalTopic,key:'rowId',fields,expansion:{message:'JoinResult',parents,leaves,enums:canonical(enums) as typeof enums}} as const);return {schema,signature,internalTopic,internalFingerprint:identityHash(new TextDecoder().decode(schemaBytes(schema)))};
}
export function defineJoin<const C extends BrowserCatalog,const D extends JoinSpec<C>>(catalog:C,definition:D&DefinitionCheck<C,D>):JoinHandle<C,D>{
 const sourceCatalog=defineCatalog(catalog),wire:JoinWire={version:1,left_alias:definition.left.as,right:{topic:definition.right.topic,schema:sourceCatalog[definition.right.topic].fingerprint,alias:definition.right.as},kind:definition.kind,cardinality:definition.cardinality,on:definition.on,limits:{max_left_rows_per_key:definition.limits.maxLeftRowsPerKey,max_output_rows:definition.limits.maxOutputRows}};const derived=joinSchema(sourceCatalog,definition.left.topic,wire);
 // Runtime schema is generated from the two literal schema authorities above.
 function frozen<T>(v:T):T{if(v&&typeof v==='object'){Object.values(v).forEach(frozen);Object.freeze(v);}return v;}
 function typedSchema(schema:Schema):asserts schema is JoinedSchema<C,D>{if(schema!==derived.schema)throw Error('unverified join schema');}
 const schema:Schema=derived.schema;typedSchema(schema);
 return frozen({joinDefinition:structuredClone(definition),topic:definition.left.topic,fingerprint:sourceCatalog[definition.left.topic].fingerprint,wire:structuredClone(wire),...derived,schema,sourceCatalog});
}
export function validateJoinQuery(handle:JoinHandle,query:unknown):void{validateQuery(handle.schema,query);if('aggregates'in query&&query.aggregates&&(Object.hasOwn(query.aggregates,handle.wire.left_alias)||Object.hasOwn(query.aggregates,handle.wire.right.alias)))throw Error('aggregate alias collides with join alias');}
export function joinResultShape(handle:{signature:string;schema:Schema;internalTopic:string;internalFingerprint:string},query:TopicQuery<Schema>):string{return JSON.stringify(['join_v1',handle.signature,'select'in query&&query.select?null:resultShape(handle.internalTopic,handle.internalFingerprint,query as AggregateQuery<Schema>),queryFields(query)]);}
export function validateJoinRow(catalog:BrowserCatalog,topic:string,wire:JoinWire,row:unknown,select:readonly string[]):void{
 if(!row||typeof row!=='object'||Array.isArray(row))throw Error('join row');const value=row as Record<string,unknown>;for(const k of Object.keys(value))if(![wire.left_alias,wire.right.alias].includes(k))throw Error('unselected join root');for(const [alias,schema,right]of [[wire.left_alias,catalog[topic].schema,false],[wire.right.alias,catalog[wire.right.topic].schema,true]] as const){const fields=select.filter(f=>f.startsWith(alias+'.')).map(f=>f.slice(alias.length+1));if(!fields.length){if(Object.hasOwn(value,alias))throw Error('unselected join alias');continue}if(right&&wire.kind==='left'&&value[alias]===null)continue;validateRow(schema,value[alias],fields);}
}
export {validateGroupedRow,groupId};
