use super::*;
use rust_differential_product_core::schema::{Definition,Field,Kind,Scalar,encode_row_id};
use serde_json::json;
fn schemas()->(Schema,Schema){let d=Definition{format:2,id:"evolved_v2".into(),version:2,key:"rowId".into(),fields:vec![Field{name:"name".into(),kind:Kind::String,optional:false,nullable:false}],expansion:None};let old=Schema::new(d.clone()).unwrap();let mut d=d;d.fields.push(Field{name:"note".into(),kind:Kind::String,optional:true,nullable:false});(old,Schema::new(d).unwrap())}
fn bindings(old:&Schema,new:&Schema)->(Binding,Binding){let a=Binding{format:3,topic:"evolved".into(),schema:old.fingerprint().into(),source_incarnation:"fixture".into(),source_topic:"source".into(),state_topic:"state".into(),group:"group".into(),descriptor:"old-exact".into(),partitions:2,retention:Some(NormalizedRetention{max_age_ms:Some(1000),max_messages:Some(10),count_scope:Some(crate::retention::CountScope::WholeTopic)})};let mut b=a.clone();b.schema=new.fingerprint().into();b.descriptor="new-exact".into();(a,b)}
fn manifest(image:&Image)->State{manifest_state(image.format,image.sequence,image.next.clone(),image.root,image.content_version,image.maintenance_sequence,image.next_order,image.last_reference_time_ms)}
#[test]fn transition_cut_mixed_compacted_epochs_and_retention_are_exact(){let(old,new)=schemas();let(a,b)=bindings(&old,&new);let mut image=Image::empty(2,a.retention.clone());let id=encode_row_id(&[Scalar::String("a".into())]).unwrap();let row=State::Row{key:id,owner:1,key_identity:[7;32],row:Some(json!({"rowId":encode_row_id(&[Scalar::String("a".into())]).unwrap(),"name":"old"})),age_origin_ms:Some(500),retention_order:Some(1)};image.next_order=1;image.next.insert(1,3);image.fold(1,row.clone(),&old,2).unwrap();let m=manifest(&image);image.fold(0,m,&old,2).unwrap();image.audit().unwrap();assert!(verify_lineage(&image,&b,Some(&a),false,false).is_ok());
 let root=image.root;let next=image.next.clone();let lineage=Lineage{epoch:1,predecessor:a.clone(),successor:b.clone(),next:next.clone(),root,sequence:0,content_version:0,maintenance_sequence:0};let marker=State::SchemaTransition{lineage:lineage.clone()};image.fold(0,marker.clone(),&new,2).unwrap();image.audit().unwrap();assert_eq!(image.root,root);assert_eq!(image.next,next);assert_eq!(image.expiry.first().unwrap().0,1500);assert!(verify_lineage(&image,&b,Some(&a),true,false).is_ok());
 // Compaction may retain old row bytes and only the successor manifest/marker.
 let mut restored=Image::empty(2,a.retention.clone());for(p,binding,state)in [(0,&b,marker),(0,&b,manifest(&image)),(1,&a,row),(1,&a,State::Next{next:3})]{let payload=encode(binding,p,&state);let(decoded,current)=decode_lineage(&b,Some((&a,&old)),p,Some(&state.key(3)),Some(&payload)).unwrap();if binding==&b{assert!(current)}restored.fold(p,decoded,&new,2).unwrap();}restored.audit().unwrap();assert_eq!(restored.root,root);assert_eq!(restored.next,next);assert_eq!(restored.expiry,image.expiry);assert!(verify_lineage(&restored,&b,Some(&a),true,false).is_ok());assert!(verify_lineage(&restored,&b,None,true,false).is_err());
 restored.lineage=None;assert!(verify_lineage(&restored,&b,Some(&a),true,false).is_err());restored.lineage=Some(lineage);restored.lineage.as_mut().unwrap().root=[0;32];assert!(verify_lineage(&restored,&b,Some(&a),true,false).is_err());}
#[test]fn unknown_binding_rollback_and_second_transition_reject(){let(old,new)=schemas();let(a,b)=bindings(&old,&new);let lineage=Lineage{epoch:1,predecessor:a.clone(),successor:b.clone(),next:BTreeMap::from([(0,0),(1,0)]),root:[0;32],sequence:0,content_version:0,maintenance_sequence:0};let marker=State::SchemaTransition{lineage};let bytes=encode(&b,0,&marker);assert!(decode_lineage(&a,None,0,Some(&marker.key(3)),Some(&bytes)).is_err());assert!(decode_lineage(&a,Some((&b,&new)),0,Some(&marker.key(3)),Some(&bytes)).is_err());let mut wrong=b.clone();wrong.descriptor="unknown".into();assert!(decode_lineage(&wrong,Some((&a,&old)),0,Some(&marker.key(3)),Some(&bytes)).is_err());}
