//! Bounded descriptor admission and dynamic messages using prost's wire machinery.
use crate::generic_source::{Descriptor,Mapping,KeyField,Identity,ComponentSource,SourcePolicy};
use prost::{Message,encoding::{self,WireType,DecodeContext},DecodeError};
use prost_types::{FileDescriptorSet,DescriptorProto,FieldDescriptorProto};
use bytes::{Buf,BufMut};
use rust_differential_product_core::{schema::{Schema,Kind,Scalar,path_get,path_insert,encode_row_id},generic::Mutation};
use serde_json::{Value,Map};
use sha2::{Digest,Sha256};
use std::{collections::{BTreeMap,BTreeSet},sync::Arc};
#[derive(Clone,Debug)]
struct Graph {messages:BTreeMap<String,DescriptorProto>,enums:BTreeMap<String,BTreeMap<String,i32>>}
fn fq(prefix:&str,name:&str)->String{if prefix.is_empty(){name.into()}else{format!("{prefix}.{name}")}}
impl Graph {
 fn new(d:&Descriptor)->Result<Arc<Self>,String>{
  if d.schema_id==0||d.message_index!=0||d.descriptor_hex.len()>131072||d.descriptor_hex.len()%2!=0||!d.descriptor_hex.bytes().all(|b|b.is_ascii_hexdigit()){return Err("expanded descriptor bounds".into())}
  let bytes=(0..d.descriptor_hex.len()).step_by(2).map(|i|u8::from_str_radix(&d.descriptor_hex[i..i+2],16).unwrap()).collect::<Vec<_>>();
  let set=FileDescriptorSet::decode(bytes.as_slice()).map_err(|e|e.to_string())?;
  if set.file.is_empty()||set.file.len()>16{return Err("expanded file bound".into())}
  let mut g=Self{messages:BTreeMap::new(),enums:BTreeMap::new()};
  fn add(g:&mut Graph,prefix:&str,m:&DescriptorProto,depth:usize)->Result<(),String>{if depth>=8||m.options.as_ref().is_some_and(|o|o.map_entry==Some(true))||!m.extension.is_empty()||!m.extension_range.is_empty(){return Err("unsupported message metadata".into())}let n=fq(prefix,m.name.as_deref().ok_or("message name")?);if g.messages.insert(n.clone(),m.clone()).is_some(){return Err("duplicate message".into())}for e in &m.enum_type{add_enum(g,&n,e)?}for child in &m.nested_type{add(g,&n,child,depth+1)?}Ok(())}
  fn add_enum(g:&mut Graph,prefix:&str,e:&prost_types::EnumDescriptorProto)->Result<(),String>{let n=fq(prefix,e.name.as_deref().ok_or("enum name")?);let mut labels=BTreeMap::new();if e.value.is_empty()||e.value.len()>256||e.value[0].number!=Some(0){return Err("enum bound/default".into())}for v in &e.value{if labels.insert(v.name.clone().ok_or("enum label")?,v.number.ok_or("enum code")?).is_some(){return Err("duplicate enum label".into())}}if g.enums.insert(n,labels).is_some(){return Err("duplicate enum domain".into())}Ok(())}
  let files=set.file.iter().map(|f|f.name.clone().unwrap_or_default()).collect::<BTreeSet<_>>();if files.len()!=set.file.len(){return Err("duplicate descriptor file".into())}
  for f in &set.file{if f.syntax.as_deref()!=Some("proto3")||!f.service.is_empty()||!f.extension.is_empty()||f.dependency.iter().any(|d|!files.contains(d)){return Err("unsupported syntax/service/import".into())}let p=f.package.as_deref().unwrap_or("");for m in &f.message_type{add(&mut g,p,m,0)?}for e in &f.enum_type{add_enum(&mut g,p,e)?}}
  if g.messages.len()+g.enums.len()>64{return Err("graph bound".into())}
  fn walk(g:&Graph,name:&str,stack:&mut Vec<String>,leaves:&mut usize)->Result<(),String>{if stack.len()>=8||stack.iter().any(|n|n==name){return Err("cycle/depth bound".into())}stack.push(name.into());let m=g.messages.get(name).ok_or("unresolved message")?;if m.field.is_empty()||m.field.len()>128{return Err("message field bound".into())}let mut names=BTreeSet::new();let mut tags=BTreeSet::new();let mut oneofs=BTreeSet::new();for f in &m.field{let tag=f.number.ok_or("field tag")?;let name=f.name.as_deref().ok_or("field name")?;if !rust_differential_product_core::schema::valid_name(name)||name=="rowId"||!names.insert(name)||!tags.insert(tag)||tag<=0||tag>536870911||(19000..=19999).contains(&tag)||f.label!=Some(1)||f.extendee.is_some()||f.default_value.is_some(){return Err("unsupported field/tag/repetition".into())}if let Some(i)=f.oneof_index{if f.proto3_optional!=Some(true)||i<0||i as usize>=m.oneof_decl.len()||!oneofs.insert(i){return Err("general oneof unsupported".into())}}else if f.proto3_optional==Some(true){return Err("optional oneof missing".into())}match f.r#type{Some(11)=>walk(g,f.type_name.as_deref().unwrap_or("").trim_start_matches('.'),stack,leaves)?,Some(14)=>{if !g.enums.contains_key(f.type_name.as_deref().unwrap_or("").trim_start_matches('.')){return Err("unresolved enum".into())}*leaves+=1},Some(1|3|4|8|9)=>{if f.type_name.is_some(){return Err("scalar type_name".into())}*leaves+=1},_=>return Err("unsupported kind".into())}if *leaves>128{return Err("leaf bound".into())}}if oneofs.len()!=m.oneof_decl.len(){return Err("unused oneof".into())}stack.pop();Ok(())}
  for n in g.messages.keys(){walk(&g,n,&mut vec![],&mut 0)?}
  let root=d.message_name.as_deref().ok_or("expanded FQ root required")?;if !g.messages.contains_key(root){return Err("unknown FQ root".into())}Ok(Arc::new(g))
 }
 fn field(&self,root:&str,path:&str)->Result<&FieldDescriptorProto,String>{let mut name=root;let parts=path.split('.').collect::<Vec<_>>();for(i,p)in parts.iter().enumerate(){let f=self.messages.get(name).ok_or("unknown message")?.field.iter().find(|f|f.name.as_deref()==Some(p)).ok_or("unknown descriptor path")?;if i+1==parts.len(){return Ok(f)}if f.r#type!=Some(11){return Err("non-message ancestor".into())}name=f.type_name.as_deref().ok_or("missing message reference")?.trim_start_matches('.');}Err("empty path".into())}
}
#[derive(Clone,Debug)]
enum Cell {String(String),Bool(bool),Double(f64),I64(i64),U64(u64),Enum(i32),Message(Dynamic)}
#[derive(Clone,Debug)]
struct Dynamic {graph:Arc<Graph>,name:String,cells:BTreeMap<u32,Cell>}
impl Dynamic {fn new(graph:Arc<Graph>,name:String)->Self{Self{graph,name,cells:BTreeMap::new()}}
 fn json(&self)->Value{let mut o=Map::new();for f in &self.graph.messages[&self.name].field{let tag=f.number.unwrap()as u32;let v=match self.cells.get(&tag){Some(Cell::String(v))=>Value::String(v.clone()),Some(Cell::Bool(v))=>Value::Bool(*v),Some(Cell::Double(v))=>serde_json::json!(v),Some(Cell::I64(v))=>Value::String(v.to_string()),Some(Cell::U64(v))=>Value::String(v.to_string()),Some(Cell::Enum(v))=>serde_json::json!({"domain":f.type_name.as_ref().unwrap().trim_start_matches('.'),"code":v}),Some(Cell::Message(v))=>v.json(),None if f.proto3_optional==Some(true)||f.r#type==Some(11)=>continue,None=>match f.r#type.unwrap(){9=>Value::String(String::new()),8=>Value::Bool(false),1=>serde_json::json!(0.0),3|4=>Value::String("0".into()),14=>serde_json::json!({"domain":f.type_name.as_ref().unwrap().trim_start_matches('.'),"code":0}),_=>unreachable!()}};o.insert(f.name.clone().unwrap(),v);}Value::Object(o)}
}
// This is the prost Message adapter for admitted descriptors, not a separate wire parser.
impl Message for Dynamic {
 fn merge_field(&mut self,tag:u32,wire:WireType,buf:&mut impl Buf,ctx:DecodeContext)->Result<(),DecodeError>{
  let Some(f)=self.graph.messages[&self.name].field.iter().find(|f|f.number==Some(tag as i32)) else{return encoding::skip_field(wire,tag,buf,ctx)};
  macro_rules! scalar{($variant:ident,$module:ident,$default:expr)=>{{let mut v=$default;encoding::$module::merge(wire,&mut v,buf,ctx)?;Cell::$variant(v)}}}
  let value=match f.r#type.unwrap(){9=>scalar!(String,string,String::new()),8=>scalar!(Bool,bool,false),1=>{let v=scalar!(Double,double,0.0);if let Cell::Double(n)=v{if !n.is_finite(){return Err(DecodeError::new("nonfinite scalar"))}}v},3=>scalar!(I64,int64,0),4=>scalar!(U64,uint64,0),14=>scalar!(Enum,int32,0),11=>{let mut child=match self.cells.remove(&tag){Some(Cell::Message(c))=>c,_=>Dynamic::new(self.graph.clone(),f.type_name.as_ref().unwrap().trim_start_matches('.').into())};encoding::message::merge(wire,&mut child,buf,ctx)?;Cell::Message(child)},_=>return Err(DecodeError::new("unadmitted kind"))};self.cells.insert(tag,value);Ok(())
 }
 fn encode_raw(&self,buf:&mut impl BufMut){for(tag,v)in &self.cells{match v{Cell::String(v)=>encoding::string::encode(*tag,v,buf),Cell::Bool(v)=>encoding::bool::encode(*tag,v,buf),Cell::Double(v)=>encoding::double::encode(*tag,v,buf),Cell::I64(v)=>encoding::int64::encode(*tag,v,buf),Cell::U64(v)=>encoding::uint64::encode(*tag,v,buf),Cell::Enum(v)=>encoding::int32::encode(*tag,v,buf),Cell::Message(v)=>encoding::message::encode(*tag,v,buf)}}}
 fn encoded_len(&self)->usize{self.cells.iter().map(|(tag,v)|match v{Cell::String(v)=>encoding::string::encoded_len(*tag,v),Cell::Bool(v)=>encoding::bool::encoded_len(*tag,v),Cell::Double(v)=>encoding::double::encoded_len(*tag,v),Cell::I64(v)=>encoding::int64::encoded_len(*tag,v),Cell::U64(v)=>encoding::uint64::encoded_len(*tag,v),Cell::Enum(v)=>encoding::int32::encoded_len(*tag,v),Cell::Message(v)=>encoding::message::encoded_len(*tag,v)}).sum()}
 fn clear(&mut self){self.cells.clear()}
}
#[derive(Clone)]
pub struct ExpandedDecoder {schema:Schema,key:Descriptor,value:Descriptor,kg:Arc<Graph>,vg:Arc<Graph>,mapping:Vec<Mapping>,identity:Identity,key_fields:Vec<KeyField>}
impl ExpandedDecoder {
 pub fn new(schema:Schema,key:&Descriptor,value:&Descriptor,mapping:Vec<Mapping>,key_fields:Vec<KeyField>,identity:Identity)->Result<Self,String>{
  let kg=Graph::new(key)?;let vg=Graph::new(value)?;let e=schema.definition().expansion.as_ref().ok_or("expanded schema required")?;
  if value.message_name.as_deref()!=Some(&e.message)||mapping.len()!=e.leaves.len(){return Err("root/mapping mismatch".into())}
  let mut covered=BTreeSet::new();for(i,l)in e.leaves.iter().enumerate(){let f=vg.field(&e.message,&l.path)?;let m=mapping.iter().find(|m|m.field==l.path).ok_or("missing mapping")?;let sf=&schema.definition().fields[i];let k=match f.r#type{Some(9)=>if sf.kind==Kind::Decimal{Kind::Decimal}else{Kind::String},Some(8)=>Kind::Boolean,Some(1)=>Kind::Number,Some(3)=>Kind::Int64,Some(4)=>Kind::Uint64,Some(14)=>Kind::Enum,_=>return Err("not a scalar leaf".into())};if sf.kind!=k||m.tag!=f.number.unwrap()as u32||(l.presence=="explicit")!=(f.proto3_optional==Some(true)){return Err("SOURCE-PRESENCE: expanded descriptor binding mismatch".into())}if !covered.insert(l.path.clone()){return Err("duplicate mapping".into())}if k==Kind::Enum&&l.enum_domain.as_deref()!=f.type_name.as_deref().map(|n|n.trim_start_matches('.')){return Err("enum domain mismatch".into())}
   if let Some(tag)=m.null_tag{let parent=l.path.rsplit_once('.').map(|v|v.0);let parent_type=if let Some(p)=parent{vg.field(&e.message,p)?.type_name.as_deref().unwrap().trim_start_matches('.')}else{&e.message};let marker=vg.messages[parent_type].field.iter().find(|f|f.number==Some(tag as i32)).ok_or("null marker")?;let path=parent.map_or_else(||marker.name.clone().unwrap(),|p|format!("{p}.{}",marker.name.as_ref().unwrap()));if !sf.nullable||marker.r#type!=Some(8)||marker.proto3_optional!=Some(true)||!covered.insert(path){return Err("null marker binding".into())}}else if sf.nullable{return Err("missing null marker".into())}
  }
  for p in &e.parents{let f=vg.field(&e.message,&p.path)?;if f.r#type!=Some(11)||f.type_name.as_deref().map(|n|n.trim_start_matches('.'))!=Some(p.message.as_str()){return Err("parent descriptor mismatch".into())}}
  fn paths(g:&Graph,n:&str,prefix:&str,out:&mut BTreeSet<String>){for f in &g.messages[n].field{let p=fq(prefix,f.name.as_ref().unwrap());if f.r#type==Some(11){paths(g,f.type_name.as_ref().unwrap().trim_start_matches('.'),&p,out)}else{out.insert(p);}}}
  let mut actual=BTreeSet::new();paths(&vg,&e.message,"",&mut actual);if actual!=covered{return Err("unmapped descriptor fields".into())}
  for(d,labels)in &e.enums{if vg.enums.get(d)!=Some(labels){return Err("enum label binding".into())}}
  let kn=key.message_name.as_deref().unwrap();let mut names=BTreeSet::new();for k in &key_fields{let f=kg.field(kn,&k.name)?;if !names.insert(k.name.clone())||f.proto3_optional!=Some(true)||f.number!=Some(k.tag as i32)||!matches!((k.kind,f.r#type),(Kind::String,Some(9))|(Kind::Boolean,Some(8))|(Kind::Number,Some(1))|(Kind::Int64,Some(3))|(Kind::Uint64,Some(4))){return Err("SOURCE-PRESENCE: explicit supported key leaves required".into())}}
  let mut kp=BTreeSet::new();paths(&kg,kn,"",&mut kp);if kp!=names{return Err("key field coverage".into())}
  let mut components=BTreeSet::new();if identity.components.is_empty()||identity.components.len()>16{return Err("identity bound".into())}for c in &identity.components{if !components.insert((c.source,c.field.clone())){return Err("duplicate identity".into())}match c.source{ComponentSource::Key=>if !names.contains(&c.field){return Err("unknown key component".into())},ComponentSource::Value=>{let f=schema.field(&c.field)?;if identity.source_policy!=SourcePolicy::Delete||f.optional||f.nullable||f.kind==Kind::Enum{return Err("unsupported value identity".into())}}}}
  Ok(Self{schema,key:key.clone(),value:value.clone(),kg,vg,mapping,identity,key_fields})
 }
 fn decode_message(d:&Descriptor,g:Arc<Graph>,bytes:&[u8])->Result<Value,String>{if bytes.len()>65536{return Err("source row bound".into())}let e=crate::wire::envelope(bytes)?;if e.schema_id!=d.schema_id||e.indexes!=[d.message_index]{return Err("unknown expanded schema envelope".into())}let mut m=Dynamic::new(g,d.message_name.clone().unwrap());m.merge(e.payload).map_err(|e|e.to_string())?;Ok(m.json())}
 pub fn decode(&self,key:Option<&[u8]>,value:Option<&[u8]>)->Result<(String,[u8;32],Mutation),String>{let kb=key.ok_or("source key required")?;let key=Self::decode_message(&self.key,self.kg.clone(),kb)?;let mut kv=BTreeMap::new();for k in &self.key_fields{let v=path_get(&key,&k.name).ok_or("missing explicit key leaf/parent")?;let scalar=match k.kind{Kind::String=>Scalar::String(v.as_str().unwrap().into()),Kind::Boolean=>Scalar::Boolean(v.as_bool().unwrap()),Kind::Number=>Scalar::Number(v.as_f64().unwrap().to_string()),Kind::Int64=>Scalar::Int64(v.as_str().unwrap().parse().map_err(|_|"key int64")?),Kind::Uint64=>Scalar::Uint64(v.as_str().unwrap().parse().map_err(|_|"key uint64")?),_=>return Err("unsupported key kind".into())};kv.insert(k.name.clone(),scalar);}
  let mut row=Map::new();if let Some(bytes)=value{let source=Self::decode_message(&self.value,self.vg.clone(),bytes)?;let e=self.schema.definition().expansion.as_ref().unwrap();for p in &e.parents{if path_get(&source,&p.path).is_some(){path_insert(&mut row,&p.path,Value::Object(Map::new()));}}for m in &self.mapping{let v=path_get(&source,&m.field);let marker=m.null_tag.and_then(|tag|{let parent=m.field.rsplit_once('.').map(|x|x.0);let n=parent.map_or(e.message.as_str(),|p|self.vg.field(&e.message,p).unwrap().type_name.as_ref().unwrap().trim_start_matches('.'));let f=self.vg.messages[n].field.iter().find(|f|f.number==Some(tag as i32)).unwrap();path_get(&source,&parent.map_or_else(||f.name.clone().unwrap(),|p|format!("{p}.{}",f.name.as_ref().unwrap())))});if let Some(marker)=marker{if marker!=&Value::Bool(true)||v.is_some(){return Err("invalid/ambiguous explicit null".into())}path_insert(&mut row,&m.field,Value::Null)}else if let Some(v)=v{path_insert(&mut row,&m.field,v.clone())}}}
  let object=Value::Object(row.clone());let components=self.identity.components.iter().map(|c|match c.source{ComponentSource::Key=>kv.get(&c.field).cloned().ok_or("missing key component".into()),ComponentSource::Value=>{let v=path_get(&object,&c.field).ok_or("value identity unavailable for tombstone")?;self.schema.scalar(self.schema.index(&c.field)?,v)}}).collect::<Result<Vec<_>,String>>()?;let id=encode_row_id(&components)?;let digest=Sha256::digest(kb).into();if value.is_none(){return Ok((id.clone(),digest,Mutation::Delete{key:id}))}row.insert("rowId".into(),Value::String(id.clone()));let admitted=self.schema.row(&Value::Object(row))?;Ok((id,digest,Mutation::Upsert{row:self.schema.full(&admitted)}))
 }
}
