//! Catalog service: one query endpoint/runtime with bounded whole-source owners.
use crate::{generic_kafka::{Owners,SourceConfig,Event},generic_owner::{Owner,Request,Publication},health,telemetry,management,subscriptions::SubscriptionLimits};
use rust_differential_product_core::{schema::{Catalog,Manifest},generic::{Runtime,Mutation}};
use serde::Deserialize;
use serde_json::{Value,json};
use std::{collections::{BTreeMap,BTreeSet,VecDeque},net::{TcpListener,TcpStream,SocketAddr},io::Read,time::{Instant,Duration},sync::Arc};
use tungstenite::{WebSocket,Message,handshake::{MidHandshake,HandshakeError,server::{ServerHandshake,Request as HttpRequest,Response,ErrorResponse}},protocol::WebSocketConfig};
#[derive(Deserialize)]#[serde(deny_unknown_fields)]
struct Config{bind:SocketAddr,origin:String,catalog:Manifest,sources:Vec<SourceConfig>,health:health::Config,#[serde(default)]subscription_limits:SubscriptionLimits,#[serde(default)]run_ms:u64,#[serde(default)]run_until_shutdown:bool}
#[derive(Clone)]struct Admission{origin:String}
impl tungstenite::handshake::server::Callback for Admission{fn on_request(self,r:&HttpRequest,mut response:Response)->Result<Response,ErrorResponse>{if r.uri().path()!="/v15"||r.uri().query().is_some()||r.headers().get("origin").and_then(|v|v.to_str().ok())!=Some(&self.origin)||r.headers().get("sec-websocket-protocol").and_then(|v|v.to_str().ok())!=Some("view-server.v15.msgpack"){return Err(tungstenite::http::Response::builder().status(403).body(Some("incompatible protocol/origin".into())).unwrap())}response.headers_mut().insert("sec-websocket-protocol","view-server.v15.msgpack".parse().unwrap());Ok(response)}}
type Handshake=MidHandshake<ServerHandshake<TcpStream,Admission>>;
enum Wire{Handshake(Option<Handshake>),Socket(WebSocket<TcpStream>)}
struct Peer{wire:Wire,born:Instant,last:Instant,blocked:Option<Instant>,authenticated:bool,nonce:String,dead:bool,last_id:u64,queue:VecDeque<Vec<u8>>,bytes:usize,patches_allowed:bool,grouped_allowed:bool,text_allowed:bool,join_allowed:bool,global_having_allowed:bool,health_allowed:bool,trace_allowed:bool,health_subscribed:bool,health_sequence:u64,health_pending:Option<Vec<u8>>,queue_peak:usize,byte_peak:usize,encoded_bytes:u64}
const INPUT:usize=4*1024*1024;const OUTPUT:usize=4*1024*1024;const QUEUED:usize=8*1024*1024;
fn blocked(e:&tungstenite::Error)->bool{matches!(e,tungstenite::Error::Io(e) if e.kind()==std::io::ErrorKind::WouldBlock)}
fn envelope(incarnation:&str,id:u64,peer:&Peer,mut value:Value)->Value{value["v"]=json!(15);value["incarnation"]=json!(incarnation);value["connection"]=json!(id.to_string());value["nonce"]=json!(peer.nonce);value}
fn enqueue(p:&mut Peer,value:Value,limit:usize){match v13_codec_experiment::generic::encode(&value){Ok(bytes) if p.queue.len()<limit+16&&p.bytes+bytes.len()<=QUEUED=>{p.bytes+=bytes.len();p.encoded_bytes+=bytes.len() as u64;p.queue.push_back(bytes);p.queue_peak=p.queue_peak.max(p.queue.len());p.byte_peak=p.byte_peak.max(p.bytes)},_=>p.dead=true}}
fn publish(peers:&mut BTreeMap<u64,Peer>,publication:Publication,cuts:&BTreeMap<String,Value>,incarnation:&str,sequence:u64,request:Option<&Request>,context:Option<&str>,limit:usize){if let Some(p)=peers.get_mut(&publication.connection){if p.dead{return}let mut value=json!({"type":"result","subscription":publication.subscription,"acquisition":publication.acquisition,"result":publication.result,"source_sequence":sequence.to_string()});if publication.dependencies.len()>1{value["source_cuts"]=json!(publication.dependencies.iter().map(|d|(d.clone(),cuts[d].clone())).collect::<BTreeMap<_,_>>());value["source_sequence"]=cuts[&publication.topic]["source_sequence"].clone();}if let Some(r)=request{value["id"]=json!(r.id);value["traceparent"]=json!(r.traceparent);}if p.trace_allowed{if let Some(c)=context{value["trace_context"]=json!(c);}}enqueue(p,envelope(incarnation,publication.connection,p,value),limit);}}
fn snapshot_for_publication(h:&health::Health,ready:&BTreeSet<String>,current:&str)->BTreeSet<String>{let snapshot=h.snapshot();ready.iter().filter(|topic|topic.as_str()==current||snapshot.sources.iter().find(|s|&s.topic==*topic).is_some_and(|s|!s.retention.enabled||s.retention.safe&&!s.retention.pending_due)).cloned().collect()}
struct Observability{h:Arc<health::Health>,t:Arc<telemetry::Telemetry>,reporter:Option<health::Reporter>,management:Option<management::Management>,finished:bool}
impl Drop for Observability{fn drop(&mut self){if !self.finished{self.h.fail();self.t.failure();}if let Some(r)=self.reporter.take(){let _=r.shutdown(Duration::from_millis(500));}if let Some(m)=self.management.take(){m.shutdown();}self.t.shutdown();}}
pub fn run(value:Value,mut callbacks:health::Callbacks)->Result<(),String>{
 let cfg:Config=serde_json::from_value(value).map_err(|e|e.to_string())?;let catalog=Catalog::new(cfg.catalog)?;
 if !cfg.bind.ip().is_loopback()||!cfg.origin.starts_with("http://127.0.0.1:")||cfg.origin.len()>256||(!cfg.run_until_shutdown&&(cfg.run_ms==0||cfg.run_ms>3600000))||(cfg.run_until_shutdown&&cfg.run_ms!=0)||cfg.sources.is_empty()||cfg.sources.iter().map(|s|s.partitions.len()).sum::<usize>()>64{return Err("catalog service bounds".into())}
 let limits=cfg.subscription_limits.validate().map_err(|e|e.to_string())?;if limits.total>120{return Err("generic subscription total bound is 120 (replacement reserve)".into())}
 for source in &cfg.sources{if source.readiness.max_sample_age_ms<cfg.health.sample_ms*2{return Err("source readiness observation age shorter than two samples".into())}}
 let token=std::env::var("V12_SESSION_TOKEN").map_err(|_|"missing session token")?;if !(32..=256).contains(&token.len()){return Err("token bound".into())}
 let mut bytes=[0u8;16];std::fs::File::open("/dev/urandom").and_then(|mut f|f.read_exact(&mut bytes)).map_err(|e|e.to_string())?;let incarnation=bytes.iter().map(|b|format!("{b:02x}")).collect::<String>();
 let first=&cfg.sources[0];let h=health::Health::new(cfg.health.clone(),incarnation.clone(),first.topic.clone(),first.source_incarnation.clone(),&first.partitions,vec![])?;
 let mut dependencies=BTreeMap::new();let mut sources=Vec::new();
 for s in &cfg.sources{use sha2::{Digest,Sha256};let resource=format!("kafka-{:x}",Sha256::digest(s.brokers.as_bytes()));let mut ids=Vec::new();for role in ["source_read","canonical_store"]{let id=format!("{resource}-{role}");ids.push(id.clone());dependencies.entry(id.clone()).or_insert(health::Dependency{id,resource_id:resource.clone(),role:role.into(),state:"starting".into(),reason:None,attribution:"unknown".into()});}sources.push(health::SourceHealth{topic:s.topic.clone(),configured_topic:Some(s.source_topic.clone()),source_id:s.source_incarnation.clone(),dependencies:ids,policy:s.readiness.clone(),partitions:s.partitions.iter().map(|p|health::PartitionHealth::unknown(*p)).collect(),retention:health::RetentionServingHealth::new(s.retention.is_some())});}
 h.update(|v|{v.sources=sources;v.dependencies=dependencies.into_values().collect();v.phase=health::Phase::Restoring;});
 let t=telemetry::Telemetry::new(&cfg.health.telemetry,&incarnation,Arc::downgrade(&h))?;
 if cfg.health.stdout{if callbacks.on_heartbeat.is_none(){callbacks.on_heartbeat=Some(Box::new(|s|{println!("{}",json!({"state":"heartbeat","health":s}));Ok(())}));}if callbacks.on_dependencies_update.is_none(){callbacks.on_dependencies_update=Some(Box::new(|d|{println!("{}",json!({"state":"dependencies","dependencies":d}));Ok(())}));}}
 let management=management::Management::start(h.clone(),t.clone(),token.clone())?;let reporter=health::Reporter::start(h.clone(),callbacks,t.clone());let mut obs=Observability{h:h.clone(),t:t.clone(),management:Some(management),reporter:Some(reporter),finished:false};
 let evolving=cfg.sources.iter().any(|s|s.evolution.is_some());
 let expanded=catalog.topics().any(|(_,s)|s.definition().format==3);
 let fingerprints=catalog.topics().map(|(name,s)|(name.to_string(),s.fingerprint().to_string())).collect::<BTreeMap<_,_>>();
 let source_limits=cfg.sources.iter().map(|s|(s.topic.clone(),s.max_rows)).collect::<BTreeMap<_,_>>();
 let max_rows=cfg.sources.iter().map(|s|s.max_rows).max().unwrap();let runtime=Runtime::new(catalog.clone(),max_rows)?;let mut owner=Owner::new(runtime,limits)?;
 let mut owners=Owners::launch_observed(cfg.sources.clone(),catalog,h.clone(),t.clone())?;
 let mut ready_sources=BTreeSet::new();let mut cuts=BTreeMap::<String,Value>::new();let mut bootstrapped=BTreeSet::new();let mut sequences=BTreeMap::new();let mut derived=BTreeMap::<String,BTreeMap<u32,u64>>::new();
 let mut complete=crate::complete::Complete::default();
 let mut peers=BTreeMap::<u64,Peer>::new();let mut next_connection=0u64;let mut listener=None;let started=Instant::now();let mut last_sample=Instant::now();
 while (cfg.run_until_shutdown||started.elapsed()<Duration::from_millis(cfg.run_ms))&&!h.stopping(){
  h.tick_at(owners.progress_ms());
  // A finite dispatch budget and round-robin source channels share one query runtime.
  for _ in 0..cfg.sources.len(){let Some(event)=owners.try_recv()? else{break};match event{
   Event::Restore{topic,schema,rows,next,sequence,content_version,maintenance_sequence:_}=>{for chunk in rows.chunks(1024){owner.runtime.apply_committed(&topic,&schema,&chunk.iter().cloned().map(|row|Mutation::Upsert{row}).collect::<Vec<_>>())?;}cuts.insert(topic.clone(),json!({"schema":schema,"source_sequence":sequence.to_string(),"content_version":content_version.to_string(),"next":next.iter().map(|(p,n)|(p.to_string(),n.to_string())).collect::<BTreeMap<_,_>>() }));sequences.insert(topic.clone(),sequence);derived.insert(topic.clone(),next);owners.ack(&topic,content_version)?;},
   Event::Committed{topic,schema,mutations,next,sequence,content_version,records,retention_complete,trace_context}=>{let span=t.span_topic("live_publish",trace_context.as_deref(),&topic);let derived_started=Instant::now();let applied=if mutations.is_empty(){Ok(0)}else{owner.runtime.apply_committed(&topic,&schema,&mutations)};let derived_elapsed=derived_started.elapsed().as_nanos();h.update(|s|s.derived_ns=(s.derived_ns.parse::<u128>().unwrap_or(0)+derived_elapsed).to_string());applied?;cuts.insert(topic.clone(),json!({"schema":schema,"source_sequence":sequence.to_string(),"content_version":content_version.to_string(),"next":next.iter().map(|(p,n)|(p.to_string(),n.to_string())).collect::<BTreeMap<_,_>>() }));complete.committed(&topic,&mutations,&cuts[&topic]);sequences.insert(topic.clone(),sequence);derived.insert(topic.clone(),next);t.source_topic(&topic,records);h.update(|s|{s.records_committed+=records;});if retention_complete{ready_sources.insert(topic.clone());}else{ready_sources.remove(&topic);}for dependency in owner.affected_dependencies(&topic){owners.guard_topic(&dependency)?;}let context=telemetry::Telemetry::context(&span);if retention_complete{let health=snapshot_for_publication(&h,&ready_sources,&topic);let publications=owner.publish_topic_ready(&topic,&health)?;for(connection,subscription,acquisition,error)in owner.take_query_errors(){if let Some(peer)=peers.get_mut(&connection){enqueue(peer,envelope(&incarnation,connection,peer,json!({"type":"query_error","subscription":subscription,"acquisition":acquisition,"error":error})),limits.per_client);}}for connection in owner.take_resource_connections(){if let Some(peer)=peers.get_mut(&connection){peer.dead=true;}t.backpressure();}for p in publications{publish(&mut peers,p,&cuts,&incarnation,sequence,None,context.as_deref(),limits.per_client);}}owners.ack(&topic,content_version)?;},
   Event::Maintenance{topic,schema,mutations,next,sequence,content_version,maintenance_sequence:_,evicted_rows:_,retention_complete,trace_context}=>{let span=t.span_topic("retention_derived",trace_context.as_deref(),&topic);let derived_started=Instant::now();let applied=if mutations.is_empty(){Ok(0)}else{owner.runtime.apply_committed(&topic,&schema,&mutations)};let derived_elapsed=derived_started.elapsed().as_nanos();h.update(|s|s.derived_ns=(s.derived_ns.parse::<u128>().unwrap_or(0)+derived_elapsed).to_string());applied?;cuts.insert(topic.clone(),json!({"schema":schema,"source_sequence":sequence.to_string(),"content_version":content_version.to_string(),"next":next.iter().map(|(p,n)|(p.to_string(),n.to_string())).collect::<BTreeMap<_,_>>() }));complete.committed(&topic,&mutations,&cuts[&topic]);sequences.insert(topic.clone(),sequence);derived.insert(topic.clone(),next);if retention_complete{ready_sources.insert(topic.clone());}else{ready_sources.remove(&topic);}for dependency in owner.affected_dependencies(&topic){owners.guard_topic(&dependency)?;}let context=telemetry::Telemetry::context(&span);if retention_complete{let health=snapshot_for_publication(&h,&ready_sources,&topic);let publications=owner.publish_topic_ready(&topic,&health)?;for(connection,subscription,acquisition,error)in owner.take_query_errors(){if let Some(peer)=peers.get_mut(&connection){enqueue(peer,envelope(&incarnation,connection,peer,json!({"type":"query_error","subscription":subscription,"acquisition":acquisition,"error":error})),limits.per_client);}}for connection in owner.take_resource_connections(){if let Some(peer)=peers.get_mut(&connection){peer.dead=true;}t.backpressure();}for p in publications{publish(&mut peers,p,&cuts,&incarnation,sequence,None,context.as_deref(),limits.per_client);}}owners.ack(&topic,content_version)?;},
   Event::Bootstrap{topic,next}=>{derived.insert(topic.clone(),next);ready_sources.insert(topic.clone());bootstrapped.insert(topic);},
   Event::Progress{..}=>{/* owners update cached diagnostics using the shared health clock */}
  }}
  if listener.is_none()&&bootstrapped.len()==cfg.sources.len(){owners.guard()?;let l=TcpListener::bind(cfg.bind).map_err(|e|e.to_string())?;l.set_nonblocking(true).map_err(|e|e.to_string())?;listener=Some(l);h.update(|s|{s.phase=health::Phase::Serving;s.startup_complete=true;s.authority_safe=true;});println!("{}",json!({"state":"ready","address":cfg.bind,"incarnation":incarnation,"catalog":fingerprints,"source_progress":derived,"source_sequences":sequences}));}
  if let Some(listener)=&listener{match listener.accept(){Ok((stream,_)) if peers.len()<16=>{stream.set_nonblocking(true).map_err(|e|e.to_string())?;stream.set_nodelay(true).map_err(|e|e.to_string())?;let config=WebSocketConfig::default().read_buffer_size(4096).write_buffer_size(0).max_write_buffer_size(OUTPUT+1024).max_message_size(Some(INPUT)).max_frame_size(Some(INPUT));let wire=match tungstenite::accept_hdr_with_config(stream,Admission{origin:cfg.origin.clone()},Some(config)){Ok(ws)=>Some(Wire::Socket(ws)),Err(HandshakeError::Interrupted(mid))=>Some(Wire::Handshake(Some(mid))),Err(_)=>None};if let Some(wire)=wire{next_connection+=1;peers.insert(next_connection,Peer{wire,born:Instant::now(),last:Instant::now(),blocked:None,authenticated:false,nonce:String::new(),dead:false,last_id:0,queue:VecDeque::new(),bytes:0,patches_allowed:false,grouped_allowed:false,text_allowed:false,join_allowed:false,global_having_allowed:false,health_allowed:false,trace_allowed:false,health_subscribed:false,health_sequence:0,health_pending:None,queue_peak:0,byte_peak:0,encoded_bytes:0});}},Ok(_)=>{},Err(e)if e.kind()==std::io::ErrorKind::WouldBlock=>{},Err(e)=>return Err(e.to_string())}}
  for id in peers.keys().copied().collect::<Vec<_>>(){let mut incoming=None;let p=peers.get_mut(&id).unwrap();if !p.authenticated&&p.born.elapsed()>Duration::from_secs(2)||p.last.elapsed()>Duration::from_secs(15)||p.blocked.is_some_and(|t|t.elapsed()>Duration::from_secs(2)){p.dead=true}if p.dead{continue}
   if let Wire::Handshake(mid)=&mut p.wire{match mid.take().unwrap().handshake(){Ok(ws)=>p.wire=Wire::Socket(ws),Err(HandshakeError::Interrupted(m))=>*mid=Some(m),Err(_)=>{p.dead=true;continue}}}
   if let Wire::Socket(ws)=&mut p.wire{match ws.flush(){Ok(())=>p.blocked=None,Err(e)if blocked(&e)=>{p.blocked.get_or_insert(Instant::now());},Err(_)=>p.dead=true}if p.blocked.is_none(){let frame=if let Some(b)=p.queue.pop_front(){p.bytes-=b.len();Some(b)}else{p.health_pending.take()};if let Some(b)=frame{match ws.send(Message::Binary(b.into())){Ok(())=>{},Err(e)if blocked(&e)=>p.blocked=Some(Instant::now()),Err(_)=>p.dead=true}}}match ws.read(){Ok(Message::Binary(b))=>{p.last=Instant::now();incoming=Some(b)},Ok(Message::Ping(_)|Message::Pong(_))=>p.last=Instant::now(),Ok(_)=>p.dead=true,Err(e)if blocked(&e)=>{},Err(_)=>p.dead=true}}
   let Some(bytes)=incoming else{continue};let value=match v13_codec_experiment::generic::decode(&bytes){Ok(v)=>v,Err(_)=>{p.dead=true;continue}};
   if !p.authenticated{let caps=value["capabilities"].as_array();if value["type"]!="hello"||value["v"]!=15||value["token"].as_str()!=Some(&token)||value["nonce"].as_str().is_none_or(|n|n.len()!=32||!n.bytes().all(|b|b.is_ascii_hexdigit()))||value["catalog"]!=json!(fingerprints)||caps.is_none_or(|c|c.len()>12||evolving&&!c.iter().any(|v|v=="schema_evolution_v1")||expanded&&!c.iter().any(|v|v=="schema_expansion_v1")||!c.iter().any(|v|v=="generic_schemas_v1")){p.dead=true;continue}p.patches_allowed=caps.unwrap().iter().any(|v|v=="selected_field_patches_v1");if p.patches_allowed{owner.allow_field_patches(id);}p.authenticated=true;p.nonce=value["nonce"].as_str().unwrap().into();p.join_allowed=caps.unwrap().iter().any(|v|v=="bounded_joins_v1");p.global_having_allowed=caps.unwrap().iter().any(|v|v=="global_having_v1");p.text_allowed=caps.unwrap().iter().any(|v|v=="text_predicates_v1");p.grouped_allowed=caps.unwrap().iter().any(|v|v=="grouped_aggregates_v1");p.health_allowed=caps.unwrap().iter().any(|v|v=="health_v1");p.trace_allowed=caps.unwrap().iter().any(|v|v=="trace_v1");enqueue(p,envelope(&incarnation,id,p,json!({"type":"ready","coverage":[0],"catalog":fingerprints,"limits":limits,"capabilities":{"generic_schemas_v1":true,"complete_source_v1":true,"effect_semantics_v1":true,"selected_field_patches_v1":p.patches_allowed,"schema_expansion_v1":true,"schema_evolution_v1":evolving,"grouped_aggregates_v1":p.grouped_allowed,"text_predicates_v1":p.text_allowed,"bounded_joins_v1":p.join_allowed,"global_having_v1":p.global_having_allowed,"health_v1":p.health_allowed,"trace_v1":p.trace_allowed}})),limits.per_client);continue}
   if value["v"]!=15||value["nonce"]!=p.nonce||value["incarnation"]!=incarnation||value["connection"]!=id.to_string(){p.dead=true;continue}
   if value["type"]=="ping"{enqueue(p,envelope(&incarnation,id,p,json!({"type":"pong"})),limits.per_client);continue}
   if value["type"]=="health_subscribe"{if !p.health_allowed||value["version"]!=1||!value["enabled"].is_boolean(){p.dead=true;continue}p.health_subscribed=value["enabled"].as_bool().unwrap();p.health_sequence=u64::MAX;if !p.health_subscribed{p.health_pending=None}continue}
   if value["type"]=="complete" {
    let response=(|| -> Result<Value,String> {
     if bytes.len()>4096{return Err("complete request bound".into())}
     let r:crate::complete::Request=serde_json::from_value(value["request"].clone()).map_err(|e|e.to_string())?;
     if !matches!(r,crate::complete::Request::Cancel{..}) {let topic=complete.topic(id,&r).ok_or("complete source absent")?;if !ready_sources.contains(&topic){return Err("complete source not ready".into())}owners.guard_topic(&topic)?;let snap=h.snapshot();if !snap.sources.iter().any(|s|s.topic==topic&&(!s.retention.enabled||s.retention.safe&&!s.retention.pending_due)){return Err("complete retention pending".into())}}
     match r {crate::complete::Request::Open{acquisition,topic,schema}=>{let cut=cuts.get(&topic).cloned().ok_or("complete source cut absent")?;complete.open(id,acquisition,topic,&schema,&mut owner.runtime,cut)},crate::complete::Request::Next{acquisition,acknowledged}=>complete.next(id,&acquisition,acknowledged),crate::complete::Request::Cancel{acquisition}=>complete.cancel(id,&acquisition)}
    })();
    let output=response.unwrap_or_else(|error|json!({"type":"complete_error","acquisition":value["request"]["acquisition"],"error":error}));enqueue(p,envelope(&incarnation,id,p,output),limits.per_client);continue;
   }
   if value["type"]!="command"||bytes.len()>65536{p.dead=true;continue}
   let raw=&value["request"];let rid=raw["id"].as_u64();let trace=raw["traceparent"].as_str();let sub=raw["command"]["subscription"].as_str();
   if rid.is_none_or(|n|n<=p.last_id||n>9_007_199_254_740_991)||trace.is_none_or(|s|s.len()!=55)||sub.is_none_or(|s|s.is_empty()||s.len()>128){p.dead=true;continue}p.last_id=rid.unwrap();
   let r=serde_json::from_value::<Request>(raw.clone());let mut result=Err("invalid typed query command".into());let command_started=Instant::now();let topic=raw["command"]["query"]["topic"].as_str().filter(|s|fingerprints.contains_key(*s)).unwrap_or("control");let span=t.span_topic("query_handle",if p.trace_allowed{value["trace_context"].as_str()}else{None},topic);let context=telemetry::Telemetry::context(&span);
   if let Ok(r)=&r{let dependencies=owner.dependencies(id,r);let known=dependencies.iter().all(|d|fingerprints.contains_key(d));if known{for dependency in &dependencies{owners.guard_topic(dependency)?;}}if h.stopping(){break}let snapshot=h.snapshot();let retention_ready=dependencies.is_subset(&ready_sources)&&dependencies.iter().all(|topic|snapshot.sources.iter().find(|s|&s.topic==topic).is_some_and(|s|!s.retention.enabled||s.retention.safe&&!s.retention.pending_due));result=if !known{Err("unknown configured join/source dependency".into())}else if !r.join_output_within_source_limit(&source_limits){Err("join output exceeds configured left source ceiling".into())}else if !p.join_allowed&&r.requires_join(){Err("join capability not negotiated".into())}else if !p.global_having_allowed&&r.requires_global_having(){Err("global/HAVING capability not negotiated".into())}else if !p.text_allowed&&r.requires_text(){Err("text predicate capability not negotiated".into())}else if raw["command"]["query"].get("group_by").is_some()&&!p.grouped_allowed{Err("grouped capability not negotiated".into())}else if !retention_ready&&!matches!(&r.command,crate::generic_owner::Command::Close{..}){Err("retention maintenance pending".into())}else{owner.command(id,r)};if owner.runtime.terminal(){return Err("terminal generic evaluator failure".into())}}

   t.operation("query_handle",command_started.elapsed(),result.is_ok());
   match result{Ok(publication)=>{let count=usize::from(publication.is_some());if let Some(publication)=publication{let seq=*sequences.get(&publication.topic).unwrap_or(&0);publish(&mut peers,publication,&cuts,&incarnation,seq,r.as_ref().ok(),context.as_deref(),limits.per_client);}let p=peers.get_mut(&id).unwrap();enqueue(p,envelope(&incarnation,id,p,json!({"type":"ack","id":rid,"traceparent":trace,"result_count":count})),limits.per_client);},Err(error)=>{let p=peers.get_mut(&id).unwrap();enqueue(p,envelope(&incarnation,id,p,json!({"type":"request_error","id":rid,"traceparent":trace,"error":error,"currentAcquisition":owner.current(id,sub.unwrap())})),limits.per_client);}}
  }
  let dead=peers.iter().filter(|(_,p)|p.dead).map(|(id,_)|*id).collect::<Vec<_>>();for id in dead{let p=peers.remove(&id).unwrap();println!("{}",json!({"state":"client_closed","connection":id,"queue_peak_frames":p.queue_peak,"queue_peak_bytes":p.byte_peak,"encoded_bytes":p.encoded_bytes}));owner.disconnect(id)?;complete.disconnect(id);}
  if last_sample.elapsed()>=Duration::from_millis(cfg.health.sample_ms){h.update(|s|{s.live_rows=owner.runtime.row_count() as u64;s.connections=peers.len()as u64;s.subscriptions=owner.count()as u64;s.backpressured_connections=peers.values().filter(|p|p.blocked.is_some()).count()as u64;s.output_queue_frames=peers.values().map(|p|(p.queue.len()+usize::from(p.health_pending.is_some()))as u64).sum();s.output_queue_bytes=peers.values().map(|p|(p.bytes+p.health_pending.as_ref().map_or(0,Vec::len))as u64).sum();for d in &mut s.dependencies{let available=s.sources.iter().filter(|src|src.dependencies.contains(&d.id)).all(|src|src.partitions.iter().all(|p|p.assigned&&p.readable_sample_ms.is_some_and(|at|h.now().saturating_sub(at)<=src.policy.max_sample_age_ms)));d.state=if available{"available"}else{"unknown"}.into();}});last_sample=Instant::now();}
  if peers.values().any(|p|p.health_subscribed&&p.health_sequence!=h.sequence()){let snapshot=h.snapshot();for(id,p)in &mut peers{if p.health_subscribed&&p.health_sequence!=snapshot.sequence{let v=envelope(&incarnation,*id,p,json!({"type":"health","version":1,"snapshot":snapshot}));if let Ok(b)=v13_codec_experiment::generic::encode(&v){if b.len()<=health::MAX_SNAPSHOT_BYTES{p.health_pending=Some(b);p.health_sequence=snapshot.sequence;}}}}}
  std::thread::sleep(Duration::from_millis(1));
 }
 h.stop();owners.stop();for(id,p)in &peers{println!("{}",json!({"state":"peer_profile","connection":id,"queue_peak_frames":p.queue_peak,"queue_peak_bytes":p.byte_peak,"encoded_bytes":p.encoded_bytes}));}for p in peers.values_mut(){if let Wire::Socket(ws)=&mut p.wire{let _=ws.close(None);}}obs.finished=true;Ok(())
}
