use rust_differential_product_core::{generic::{Runtime,Mutation,Query},schema::{Catalog,Schema,Manifest,Topic},join::JoinDefinition};use serde_json::{json,Value};
fn fixture()->(Runtime,String,String){let schema=|id:&str|Schema::new(serde_json::from_value(json!({"format":1,"version":1,"id":id,"key":"id","fields":[{"name":"id","kind":"string","optional":false,"nullable":false},{"name":"k","kind":"string","optional":true,"nullable":true},{"name":"amount","kind":"decimal","optional":false,"nullable":false}]})).unwrap()).unwrap();let l=schema("Left");let r=schema("Right");let lf=l.fingerprint().into();let rf=r.fingerprint().into();let c=Catalog::new(Manifest{format:1,schemas:vec![l.definition().clone(),r.definition().clone()],topics:vec![Topic{topic:"left".into(),schema:l.fingerprint().into()},Topic{topic:"right".into(),schema:r.fingerprint().into()}]}).unwrap();(Runtime::new(c,100).unwrap(),lf,rf)}
fn definition(rf:&str,kind:&str)->JoinDefinition{serde_json::from_value(json!({"version":1,"left_alias":"l","right":{"topic":"right","schema":rf,"alias":"r"},"kind":kind,"cardinality":"many_to_one","on":{"left":"k","right":"k"},"limits":{"max_left_rows_per_key":4,"max_output_rows":100}})).unwrap()}
fn query(v:Value)->Query{serde_json::from_value(v).unwrap()}
fn apply(r:&mut Runtime,topic:&str,fp:&str,v:Value){r.apply_committed(topic,fp,&[Mutation::Upsert{row:v}]).unwrap();}
#[test]fn left_incremental_identity_global_having_and_isolated_duplicate_failure(){let(mut r,l,rr)=fixture();apply(&mut r,"left",&l,json!({"id":"a","k":"x","amount":"3"}));apply(&mut r,"left",&l,json!({"id":"b","k":null,"amount":"4"}));r.open_join("j","left",&l,definition(&rr,"left"),query(json!({"select":["l.amount","r.amount"],"order_by":[]}))).unwrap();let before=r.read("j",0,10,65536).unwrap();assert_eq!(before.total_rows,2);assert!(before.rows.iter().all(|v|v["r"].is_null()));let keys=before.keys;let seed=r.metrics()["join_seed_rows"].clone();
apply(&mut r,"right",&rr,json!({"id":"ra","k":"x","amount":"9"}));let got=r.read("j",0,10,65536).unwrap();assert_eq!(got.keys,keys);assert!(got.rows.iter().any(|v|v["r"]["amount"]=="9"));assert_eq!(r.metrics()["join_seed_rows"],seed);
r.open_join("g","left",&l,definition(&rr,"left"),query(json!({"global":true,"aggregates":{"sum":{"aggFunc":"sum","field":"r.amount"}},"having":{"op":"gt","field":"sum","value":"0"},"order_by":[]}))).unwrap();assert_eq!(r.read("g",0,10,65536).unwrap().rows,vec![json!({"sum":"9"})]);println!("JOIN_VECTOR {}",json!({"catalog":r.catalog().manifest(),"definition":definition(&rr,"left"),"raw":got,"global":r.read("g",0,10,65536).unwrap()}));
r.apply_committed("right",&rr,&[Mutation::Delete{key:"ra".into()}]).unwrap();assert_eq!(r.read("j",0,10,65536).unwrap().keys,keys);assert_eq!(r.read("g",0,10,65536).unwrap().total_rows,0);
apply(&mut r,"right",&rr,json!({"id":"ra","k":"x","amount":"9"}));apply(&mut r,"right",&rr,json!({"id":"duplicate","k":"x","amount":"1"}));assert!(r.read("j",0,10,65536).unwrap_err().contains("right join key is not unique"));assert!(!r.terminal());r.open("raw","right",&rr,query(json!({"select":["id"],"order_by":[]}))).unwrap();assert_eq!(r.read("raw",0,10,65536).unwrap().total_rows,2);
}
#[test]fn independent_both_side_oracle_fanout_and_reconstruction(){
 let(mut r,l,rr)=fixture();let mut left=std::collections::BTreeMap::<String,(Option<String>,String)>::new();let mut right=std::collections::BTreeMap::<String,(String,String)>::new();
 for i in 0..12 {let id=format!("l{i}");let k=format!("k{}",i%4);apply(&mut r,"left",&l,json!({"id":id,"k":k,"amount":i.to_string()}));left.insert(id,(Some(k),i.to_string()));}
 let q=json!({"select":["l.id","l.amount","r.id","r.amount"],"order_by":[{"field":"l.id","direction":"asc"}]});for kind in ["left","inner"]{r.open_join(kind,"left",&l,definition(&rr,kind),query(q.clone())).unwrap();}
 let seed=r.metrics()["join_seed_rows"].clone();
 for cut in 0..120 {let id=format!("r{}",cut%4);let key=format!("k{}",cut%4);if cut%7==0{r.apply_committed("right",&rr,&[Mutation::Delete{key:id.clone()}]).unwrap();right.remove(&id);}else{let amount=(cut+100).to_string();apply(&mut r,"right",&rr,json!({"id":id,"k":key,"amount":amount}));right.insert(id,(key,amount));}
 if cut%3==0 {let i=cut%12;let id=format!("l{i}");let key=if cut%6==0{None}else{Some(format!("k{}",i%4))};let amount=cut.to_string();apply(&mut r,"left",&l,json!({"id":id,"k":key,"amount":amount}));left.insert(id,(key,amount));}
 for kind in ["left","inner"]{let mut expected=vec![];for (id,(key,amount))in &left{let found=key.as_ref().and_then(|k|right.iter().find(|(_,v)|&v.0==k));if found.is_none()&&kind=="inner"{continue}expected.push(json!({"l":{"id":id,"amount":amount},"r":found.map(|(id,(_,amount))|json!({"id":id,"amount":amount}))}));}assert_eq!(r.read(kind,0,100,65536).unwrap().rows,expected,"{kind} cut {cut}");}
 assert_eq!(r.metrics()["join_seed_rows"],seed);
 }
 let before=r.read("left",0,100,65536).unwrap();let(mut recovered,ll,rrr)=fixture();for(id,(key,amount))in &left{apply(&mut recovered,"left",&ll,json!({"id":id,"k":key,"amount":amount}));}for(id,(key,amount))in &right{apply(&mut recovered,"right",&rrr,json!({"id":id,"k":key,"amount":amount}));}recovered.open_join("j","left",&ll,definition(&rrr,"left"),query(q)).unwrap();let after=recovered.read("j",0,100,65536).unwrap();assert_eq!(before.rows,after.rows);assert_eq!(before.keys,after.keys);
 let mut invalid=definition(&rr,"left");invalid.limits.max_left_rows_per_key=1;assert!(r.open_join("left","left",&l,invalid,query(json!({"select":["l.id"],"order_by":[]}))).is_err());assert_eq!(r.read("left",0,100,65536).unwrap().keys,before.keys);
}
#[test]fn nested_enum_unknown_code_presence_and_affected_index_bound(){
 use rust_differential_product_core::schema::{Scalar,encode_row_id};let c:Manifest=serde_json::from_str(include_str!("../../../../../fixtures/expanded-topics/catalog.json")).unwrap();let catalog=Catalog::new(c).unwrap();let lf=catalog.topics().find(|(t,_)|*t=="shit").unwrap().1.fingerprint().to_owned();let rf=catalog.topics().find(|(t,_)|*t=="nested_positions").unwrap().1.fingerprint().to_owned();let mut r=Runtime::new(catalog,10000).unwrap();let id=|s:&str|encode_row_id(&[Scalar::String(s.into())]).unwrap();
 for i in 0..1000 {apply(&mut r,"shit",&lf,json!({"rowId":id(&format!("l{i}")),"oo":{"name":"","status":{"domain":"example.common.Status","code":i}},"label":""}));}
 let join:JoinDefinition=serde_json::from_value(json!({"version":1,"left_alias":"l","right":{"topic":"nested_positions","schema":rf,"alias":"r"},"kind":"left","cardinality":"many_to_one","on":{"left":"oo.status","right":"details.status"},"limits":{"max_left_rows_per_key":4,"max_output_rows":1000}})).unwrap();
 r.open_join("j","shit",&lf,join,query(json!({"select":["l.oo.status","r.details.note"],"where":{"op":"contains","field":"l.oo.name","value":""},"order_by":[{"field":"l.oo.status","direction":"asc"}]}))).unwrap();let old=r.read("j",77,1,65536).unwrap();assert!(old.rows[0]["r"].is_null());let touched=r.metrics()["join_touched"].as_u64().unwrap();apply(&mut r,"nested_positions",&rf,json!({"rowId":id("r"),"details":{"name":"right","status":{"domain":"example.common.Status","code":77}}}));assert_eq!(r.metrics()["join_touched"].as_u64().unwrap()-touched,1);let next=r.read("j",77,1,65536).unwrap();assert_eq!(old.keys,next.keys);assert_eq!(next.rows[0]["r"],json!({"details":{}}));
 apply(&mut r,"nested_positions",&rf,json!({"rowId":id("r"),"details":{"name":"right","status":{"domain":"example.common.Status","code":78},"note":""}}));assert!(r.read("j",77,1,65536).unwrap().rows[0]["r"].is_null());assert_eq!(r.read("j",78,1,65536).unwrap().rows[0]["r"],json!({"details":{"note":""}}));
}
