use rust_differential_product_core::{generic::{Runtime,Mutation,Query},schema::{Schema,Catalog,Manifest,Topic}};
use serde_json::{json,Value};
fn fixture()->(Runtime,String){let s=Schema::new(serde_json::from_value(json!({"format":1,"id":"text","version":1,"key":"id","fields":[{"name":"id","kind":"string","optional":false,"nullable":false},{"name":"text","kind":"string","optional":true,"nullable":true},{"name":"n","kind":"number","optional":false,"nullable":false}]})).unwrap()).unwrap();let fp=s.fingerprint().to_string();(Runtime::new(Catalog::new(Manifest{format:1,schemas:vec![s.definition().clone()],topics:vec![Topic{topic:"text".into(),schema:fp.clone()}]}).unwrap(),100).unwrap(),fp)}
fn q(op:&str,value:&str)->Query{serde_json::from_value(json!({"select":["id"],"where":{"op":op,"field":"text","value":value},"order_by":[]})).unwrap()}
#[test]fn literal_sensitive_empty_presence_and_incremental_replacement(){let(mut r,fp)=fixture();let rows=[json!({"id":"a","text":"Café.+","n":1}),json!({"id":"b","text":"cafe\u{301}.+","n":2}),json!({"id":"c","text":null,"n":3}),json!({"id":"d","n":4}),json!({"id":"e","text":"","n":5})];r.apply_committed("text",&fp,&rows.into_iter().map(|row|Mutation::Upsert{row}).collect::<Vec<_>>()).unwrap();for(op,value,ids)in [("contains",".+",vec!["a","b"]),("startsWith","Caf",vec!["a"]),("endsWith","é.+",vec!["a"]),("contains","café",vec![]),("contains","",vec!["a","b","e"])]{r.open("q","text",&fp,q(op,value)).unwrap();let got=r.read("q",0,10,65536).unwrap();assert_eq!(got.keys,ids);assert!(got.rows.iter().all(|v|v.as_object().unwrap().len()==1));}
let before=r.metrics()["seed_rows"].as_u64().unwrap();r.apply_committed("text",&fp,&[Mutation::Upsert{row:json!({"id":"c","text":"new","n":3})},Mutation::Delete{key:"a".into()}]).unwrap();assert_eq!(r.read("q",0,10,65536).unwrap().keys,vec!["b","c","e"]);assert_eq!(r.metrics()["seed_rows"],before);let mut bad=serde_json::to_value(q("contains","x")).unwrap();bad["where"]["field"]=json!("n");assert!(r.open("q","text",&fp,serde_json::from_value(bad).unwrap()).is_err());assert_eq!(r.read("q",0,10,65536).unwrap().keys,vec!["b","c","e"]);
r.open("q","text",&fp,q("startsWith","new")).unwrap();assert_eq!(r.read("q",0,10,65536).unwrap().keys,vec!["c"]);r.apply_committed("text",&fp,&[Mutation::Upsert{row:json!({"id":"c","text":"old","n":3})}]).unwrap();assert_eq!(r.read("q",0,10,65536).unwrap().total_rows,0);r.apply_committed("text",&fp,&[Mutation::Upsert{row:json!({"id":"c","text":"newer","n":3})}]).unwrap();assert_eq!(r.read("q",0,10,65536).unwrap().keys,vec!["c"]);
for member in ["caseSensitive","accentSensitive","mode"]{let mut bad=serde_json::to_value(q("contains","x")).unwrap();bad["where"][member]=Value::Bool(false);assert!(serde_json::from_value::<Query>(bad).is_err());}assert!(r.open("q","text",&fp,q("contains",&"x".repeat(4097))).is_err());}
#[test]fn nested_string_dependency_is_not_projected(){let c:Manifest=serde_json::from_str(include_str!("../../../../../fixtures/expanded-topics/catalog.json")).unwrap();let c=Catalog::new(c).unwrap();let fp=c.topics().find(|(t,_)|*t=="shit").unwrap().1.fingerprint().to_string();let schema=c.schema("shit",&fp).unwrap();let key=rust_differential_product_core::schema::encode_row_id(&[rust_differential_product_core::schema::Scalar::String("key".into())]).unwrap();let row=schema.row(&json!({"rowId":key,"oo":{"name":"Café","status":{"domain":"example.common.Status","code":0},"price":"1"},"label":""})).unwrap();let full=schema.full(&row);let mut r=Runtime::new(c,10).unwrap();r.apply_committed("shit",&fp,&[Mutation::Upsert{row:full}]).unwrap();let q=serde_json::from_value(json!({"select":["oo.price"],"where":{"op":"endsWith","field":"oo.name","value":"fé"},"order_by":[]})).unwrap();r.open("q","shit",&fp,q).unwrap();assert_eq!(r.read("q",0,10,65536).unwrap().rows,vec![json!({"oo":{"price":"1"}})]);}
