/** Keep Tailwind's explicit sources aligned with the UI workspace dependency graph. */
import { existsSync, globSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

export const START = "/* workspace-sources:start — generated by vp run css:sources */";
export const END = "/* workspace-sources:end */";
const dependencyFields = [
  "dependencies",
  "optionalDependencies",
  "peerDependencies",
  "devDependencies",
] as const;
const ignored = [
  "**/node_modules/**",
  "**/dist/**",
  "**/target/**",
  "**/.git/**",
  "**/.local/**",
  "**/.output/**",
  "**/.tanstack/**",
  "**/.vite/**",
  "**/fixtures/**",
];
const posix = (path: string) => path.split(sep).join("/");
function object(value: unknown, label: string): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value))
    throw Error(`${label}: expected an object`);
  return Object.fromEntries(Object.entries(value));
}
function strings(value: unknown, label: string): string[] {
  if (!Array.isArray(value) || !value.every((item): item is string => typeof item === "string"))
    throw Error(`${label}: expected a string array`);
  return value;
}
function within(root: string, path: string) {
  const rel = relative(root, path);
  if (isAbsolute(rel) || rel === ".." || rel.startsWith(`..${sep}`))
    throw Error(`Path outside workspace: ${path}`);
}
export interface Workspace {
  readonly name: string;
  readonly directory: string;
  readonly manifest: Record<string, unknown>;
  readonly dependencies: Set<string>;
}

export function readWorkspaces(root: string): Workspace[] {
  const config = object(
    parse(readFileSync(join(root, "pnpm-workspace.yaml"), "utf8")),
    "workspace config",
  );
  const patterns = strings(config.packages, "workspace packages");
  const included = patterns.filter((pattern) => !pattern.startsWith("!"));
  if (!included.length) throw Error("Workspace has no package patterns");
  for (const pattern of patterns) within(root, resolve(root, pattern.replace(/^!/, "")));
  const manifests = globSync(
    included.map((pattern) => `${pattern}/package.json`),
    {
      cwd: root,
      exclude: [
        ...ignored,
        ...patterns
          .filter((pattern) => pattern.startsWith("!"))
          .map((pattern) => `${pattern.slice(1)}/**`),
      ],
    },
  ).sort();
  const packages = manifests.map((path) => {
    const manifest = object(JSON.parse(readFileSync(join(root, path), "utf8")), path);
    if (typeof manifest.name !== "string" || !manifest.name)
      throw Error(`${path}: package name required`);
    return {
      name: manifest.name,
      directory: resolve(root, dirname(path)),
      manifest,
      dependencies: new Set<string>(),
    };
  });
  const byName = new Map(packages.map((pkg) => [pkg.name, pkg]));
  if (byName.size !== packages.length) throw Error("Duplicate workspace package name");
  const byDirectory = new Map(packages.map((pkg) => [pkg.directory, pkg]));
  for (const pkg of packages) {
    for (const field of dependencyFields) {
      for (const [name, version] of Object.entries(
        object(pkg.manifest[field] ?? {}, `${pkg.name}.${field}`),
      )) {
        if (typeof version !== "string")
          throw Error(`${pkg.name}.${field}.${name}: version must be a string`);
        let target = byName.get(name);
        if (version.startsWith("workspace:")) {
          const specifier = version.slice("workspace:".length);
          if (specifier.startsWith("."))
            target = byDirectory.get(resolve(pkg.directory, specifier));
          else if (specifier.includes("@"))
            target = byName.get(specifier.slice(0, specifier.lastIndexOf("@")));
          if (!target)
            throw Error(`${pkg.name}: unresolved workspace dependency ${name} (${version})`);
        }
        if (target) pkg.dependencies.add(target.name);
      }
    }
  }
  return packages;
}

/** Includes the starting package; visited sets make cycles and diamonds safe. */
export function closure(name: string, packages: ReadonlyMap<string, Workspace>): Set<string> {
  const visited = new Set<string>();
  const pending = [name];
  while (pending.length) {
    const next = pending.pop()!;
    if (visited.has(next)) continue;
    visited.add(next);
    for (const dependency of packages.get(next)?.dependencies ?? []) pending.push(dependency);
  }
  return visited;
}

export function updateBlock(css: string, sources: readonly string[]): string {
  const starts = css.split(START).length - 1;
  const ends = css.split(END).length - 1;
  if (starts !== ends || starts > 1 || (starts === 1 && css.indexOf(START) > css.indexOf(END)))
    throw Error("Malformed or duplicate workspace-sources markers");
  const newline = css.includes("\r\n") ? "\r\n" : "\n";
  const block = sources.length
    ? [START, ...sources.map((source) => `@source ${JSON.stringify(source)};`), END].join(newline)
    : "";
  if (starts)
    return css.slice(0, css.indexOf(START)) + block + css.slice(css.indexOf(END) + END.length);
  if (!block) return css;
  return css + (css.endsWith(newline) ? newline : newline + newline) + block + newline;
}

export interface Change {
  readonly path: string;
  readonly before: string;
  readonly after: string;
}
export function plan(root: string) {
  const workspaces = readWorkspaces(root);
  const byName = new Map(workspaces.map((pkg) => [pkg.name, pkg]));
  // Resolve identity from the owning directory, not a hard-coded npm package name.
  const ui = workspaces.find((pkg) => pkg.directory === resolve(root, "packages/ui"));
  if (!ui) throw Error("packages/ui is missing from the workspace");
  const reachable = new Map(workspaces.map((pkg) => [pkg.name, closure(pkg.name, byName)]));
  const consumers = new Set(
    workspaces.filter((pkg) => reachable.get(pkg.name)!.has(ui.name)).map((pkg) => pkg.name),
  );
  const changes: Change[] = [];
  const inventory: Array<{
    name: string;
    ui: "self" | "direct" | "transitive" | "none";
    stylesheets: string[];
    sources: string[];
  }> = [];
  for (const pkg of workspaces) {
    // Only the owner and UI-related dependencies: never reverse dependents or unrelated SDK/Rust packages.
    const sources = workspaces.filter(
      (dependency) =>
        consumers.has(dependency.name) && reachable.get(pkg.name)!.has(dependency.name),
    );
    const files = globSync("**/*.css", { cwd: pkg.directory, exclude: ignored }).sort();
    const stylesheets: string[] = [];
    for (const file of files) {
      const path = join(pkg.directory, file);
      const css = readFileSync(path, "utf8");
      const isEntry =
        /(?:^|\/)globals\.css$/.test(posix(file)) ||
        /@import\s+["'](?:tailwindcss|[^"']+\/styles\.css)["']/.test(css) ||
        css.includes(START) ||
        css.includes(END);
      if (!isEntry) continue;
      stylesheets.push(posix(relative(root, path)));
      const paths = new Set<string>();
      if (consumers.has(pkg.name)) {
        for (const dependency of sources) {
          // Library dist remains registered even in a fresh checkout before outputs exist.
          for (const directory of ["src", ...(dependency.manifest.exports ? ["dist"] : [])]) {
            let source = posix(relative(dirname(path), join(dependency.directory, directory)));
            if (!source.startsWith(".")) source = "./" + source;
            paths.add(source);
          }
        }
      }
      let after: string;
      try {
        after = updateBlock(css, [...paths].sort());
      } catch (error) {
        throw Error(
          `${relative(root, path)}: ${error instanceof Error ? error.message : String(error)}`,
        );
      }
      if (css !== after) changes.push({ path, before: css, after });
    }
    inventory.push({
      name: pkg.name,
      ui:
        pkg.name === ui.name
          ? "self"
          : pkg.dependencies.has(ui.name)
            ? "direct"
            : consumers.has(pkg.name)
              ? "transitive"
              : "none",
      stylesheets,
      sources: consumers.has(pkg.name) ? sources.map((source) => source.name).sort() : [],
    });
  }
  return { changes, inventory };
}

export function synchronize(root: string, check: boolean) {
  // Validate the whole plan first; invalid input cannot leave half-updated stylesheets.
  const result = plan(root);
  if (!check) for (const change of result.changes) writeFileSync(change.path, change.after);
  return result;
}

function main() {
  const args = process.argv.slice(2);
  if (args.some((arg) => arg !== "--check") || args.length > 1)
    throw Error("Usage: node tools/tailwind-sources/index.ts [--check]");
  const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
  if (!existsSync(join(root, "pnpm-workspace.yaml"))) throw Error("Workspace root not found");
  const check = args.includes("--check");
  const { changes, inventory } = synchronize(root, check);
  for (const entry of inventory)
    console.log(
      `${entry.name}: UI ${entry.ui}; ${entry.stylesheets.join(", ") || "no CSS entrypoint"}`,
    );
  if (changes.length) {
    const paths = changes.map((change) => posix(relative(root, change.path)));
    console[check ? "error" : "log"](
      `${check ? "Stale" : "Updated"} Tailwind sources:\n${paths.join("\n")}`,
    );
    if (check) {
      console.error("Run vp run css:sources and commit the resulting CSS.");
      process.exitCode = 1;
    }
  } else console.log("Tailwind workspace sources are current.");
}
if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
